### ISSUE TITLE
Adium "sip:" contact add

### ISSUE THREAD

**Issue by stevejarvis** [tieto/sipe#1]
When contacts of the form "sip:name@company.com" are added they actually get saved as "sipname@company.com".

If I receive a chat from a contact, the address is correctly displayed as "sip:name@company.com" and I can save them to my contacts list. It's only the process of manually adding that seems effected.

It's as stated in this thread, comments #51 and #60: https://trac.adium.im/ticket/1541
Comment #60 claims it's fixed, but it seems to persist, and the posted links are down.

OS X 10.9, Adium 1.5.9, SIPE 1.18.0.

**Comment by xhaakon** [comment]
Hello,

sorry, this is not the right place to report SIPE + Adium specific bugs. The repo here serves only a closed group of developers as a staging area for their work in progress before pushing the changes into SIPE upstream.

Please move your ticket to the bug tracker on [Sourceforge](http://sourceforge.net/p/sipe/bugs/), where the Adium guys are present.

Thank you,

Jakub
