### ISSUE TITLE
Build breakage with pidgin-2.x

### ISSUE THREAD

**Issue by dwmw2** [tieto/sipe#100]
Commit 93fa58e00dba302257ec55178f88924aefbddab7 ("media: send MS-RTP video source request") adds gstreamer-rtp-x.x to the pkg-config requirements only for Pidgin 3.

Thus, when I build for Pidgin 2 I get:
plugin loaded error: .libs/libsipe.so: undefined symbol: gst_rtcp_buffer_add_packet

**Comment by xhaakon** [comment]
Missed that, thanks; merging your fix.

fa38ecf8159bfa50023c8283cc611209401c9d1c should further simplify that GStreamer check a bit.
