### ISSUE TITLE
Screen sharing no longer working 

### ISSUE THREAD

**Issue by overisberg** [tieto/sipe#106]
I have problems with Screen Sharing recently I get "Couldn't create stream" / "Connection timed out" when I try to accept a shared screen.

This problem started around the same time users upgraded from Lync to Skype for Business.
Meetings are labeled as "Skype Meeting" instead of "Lync Meeting" in my calendar... I not know if this has anything to do with this problem but it is my guess.

I have sent debug logs to xhaakon.

**Comment by xhaakon** [comment]
@overisberg  Please try the following update:

```
libnice - 0.1.14~sipe-0+201606201131~ubuntu16.04.1
libnice - 0.1.14~sipe-0+201606201131~ubuntu15.10.1
libnice - 0.1.14~sipe-0+201606201157~ubuntu14.04.1
```

It seems conferencing through relays was broken by a `libnice` change we adopted from upstream.

Let me know if you want me to send you a URL of a test meeting.

**Comment by overisberg** [comment]
Working fine with latest update... Thanks ;)
