### ISSUE TITLE
Is it possible to get a list of users in a conference call? 

### ISSUE THREAD

**Issue by rbeldin** [tieto/sipe#110]
It is useful to get a list of participants in a conference call.   Is there a way to capture this?  Currently,  I drill down to the .purple/logs/sipe/account/chat*/date.txt, but that is not always accurate.

**Comment by xhaakon** [comment]
You can see the participants in that conference's respective text chat window. Isn't it what you're looking for?

![untitled](https://cloud.githubusercontent.com/assets/2165526/17184607/8490bdfa-542d-11e6-87a7-40a05119317c.png)

If you close the chat window, I guess the only way to bring it back is to reconnect to the meeting using its URL.

**Comment by xhaakon** [comment]
No follow-up of this issue for more than two weeks, so I figure the question has been answered.
