### ISSUE TITLE
Display fonts went large and unadjustable

### ISSUE THREAD

**Issue by bhmcintosh** [tieto/sipe#124]
Running Pidgin 3.0.0devel under xubuntu 14.04, all updates up-to-date.  When I installed sipe collab, the conversation window font jumped several sizes, and now is no longer adjustable.

**Comment by xhaakon** [comment]
What are you comparing your current conversation window appearance to? Some older version of Pidgin 3? Pidgin 2.x?

Could you please provide a screenshot? If you're new to Pidgin 3, the interface may need some getting used to. The fonts _are_ somewhat larger than in previous versions - it should look something like this:

![conversation](https://cloud.githubusercontent.com/assets/2165526/19881525/c8f8e8e4-a006-11e6-8897-6ebb1baa9292.png)

If you have any feedback or suggestions regarding the UI, please contact the upstream Pidgin developers: https://developer.pidgin.im/.

**Comment by bhmcintosh** [comment]
On 2016-11-01 02:50, Jakub Adam wrote:

> What are you comparing your current conversation window appearance to? Some older version of Pidgin 3? Pidgin 2.x?
> 
> Previous version was 2.10.  So it wasn't anything in particular that sipe-collab did, but something Pidgin itself did? PLEASE tell me that's something I can tweak in a config file, 'cause I LOATHE the new, larger default font. :)
> 
> Could you please provide a screenshot? If you're new to Pidgin 3, the interface may need some getting used to. The fonts /are/ somewhat larger than in previous versions - it should look something like this:
> 
> Screenshot attached. Font used to be about the same size as the xchat window to the left. I DEFINITELY don't like the bigger font.

## 

---

Bruce H. McIntosh
Senior Network Engineer
University of Florida Information Technology
Network Services
bhm@ufl.edu
352-273-1066

**Comment by xhaakon** [comment]
> Previous version was 2.10. So it wasn't anything in particular that sipe-collab did, but something Pidgin itself did?

`pidgin-sipe` package from `sipe-collab PPA` depends on Pidgin 3 (which is made available through the same PPA), so installing Sipe updated your Pidgin as well.

> PLEASE tell me that's something I can tweak in a config file, 'cause I LOATHE the new, larger default font. :)

I'm not exactly a fan of this change either and there's no config option at the moment, I'm afraid. `sipe-collab PPA` just provides packages compiled from the latest Pidgin source codes its developers are working on. My suggestion is that you get in touch directly with [Pidgin upstream](https://developer.pidgin.im/) and give them some constructive criticism on their UI :) Those devs should be more competent to deal with this particular issue than I am.
