### ISSUE TITLE
Compilation error:  recipe for target 'all-recursive' failed

### ISSUE THREAD

**Issue by wklm** [tieto/sipe#130]
Hey,

I have some troubles with compilation. 

I have all[ that packages](https://launchpad.net/~sipe-collab/+archive/ubuntu/ppa) and i'm running on fedora 24
Cheers,
Wojtek 

Making all in po
make[2]: Entering directory '/home/wojtek/Desktop/sipe/po'
make[2]: Nothing to be done for 'all'.
make[2]: Leaving directory '/home/wojtek/Desktop/sipe/po'
make[2]: Entering directory '/home/wojtek/Desktop/sipe'
make[2]: Leaving directory '/home/wojtek/Desktop/sipe'
Makefile:504: recipe for target 'all-recursive' failed
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory '/home/wojtek/Desktop/sipe'
Makefile:436: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by xhaakon** [comment]
Those last few lines of your build output show no clue. The actual error must have happened earlier (and should show up in the full log).

If you're not comfortable building the whole setup yourself, you may be interested in [dwmw2's](https://github.com/dwmw2) [Fedora packages](https://copr.fedorainfracloud.org/coprs/dwmw2/sipecollab/).

**Comment by wklm** [comment]
hey @xhaakon 

Many thanks for the hint! I know it's not really relevant for this repo, bu maybe you will know :) As I'm trying to install this package it fails with: "Failed to synchronize cache for repo 'dwmw2-pidgin3-sipe', disabling." What can be wrong about it? 

cc: @dwmw2

**Comment by xhaakon** [comment]
Hi,

On 16.11.2016 09:39, wklm wrote:

> Many thanks for the hint! I know it's not really relevant for this repo, bu maybe you will know :) As I'm trying to install this package it fails
> with: "Failed to synchronize cache for repo 'dwmw2-pidgin3-sipe', disabling." What can be wrong about it?

I'm neither a maintainer of that repo nor a Fedora user, so I'm not able to help you with this issue, sorry.

Regards,

Jakub

**Comment by wklm** [comment]
hey @xhaakon, you're right, this is why i removed my comment. Anyway, i managed to install and run this fedora packages bundle and now I have Pidgin 3.0.0devel-0.1.collab.20150305git6d1ae024.fc21 and pidgin-sipe-1.19.0-1.1collab. Everything seems to be fine, besides of initial handshake at call while calling to skype4business clients. Would you have any hints how can i deal witth that?

**Comment by xhaakon** [comment]
> initial handshake at call while calling to skype4business clients

Skype for Business clients aren't very well supported yet. You can at least open bugs for issues you encounter.

**Comment by xhaakon** [comment]
I don't see any remaining questions in this thread; closing. You may open individual tickets for any SfB-related problems.
