### ISSUE TITLE
Advertise the mute state to the Lync server

### ISSUE THREAD

**Issue by cristim** [tieto/sipe#14]
During a group call it appears as if the users of pidgin clients are talking all the time, even when they are actually on mute.

When everyone else from the call is muted, it is distracting to Skype for Business users from the same call, which may think that the pidgin-sipe user has something to say.

The mute state should be properly advertised to the Lync server.

**Comment by xhaakon** [comment]
Implemented in 24c583888d08c69cf5209f4663b3c313049f7dba & available for installation from [sipe-collab PPA](https://launchpad.net/~sipe-collab/+archive/).

If there aren't any problems discovered, I'll push the change upstream within a few days. ETA in Sipe version 1.21.0.
