### ISSUE TITLE
provide os x installation via brew

### ISSUE THREAD

**Issue by ssbarnea** [tieto/sipe#15]
Adium can be easily installed on OS X via `brew cask install adium` but this does not include the SIPE plugin which makes much harder to install it on a machine.

Please provide a `brea/cask` recipe that installs the plugin in Adium.

**Comment by xhaakon** [comment]
Hi, this GitHub project is where we play around with improvements to Sipe plugin's voice and video capabilities before we contribute the changes upstream.

For general feature requests that do not relate to this experimental version of Sipe, please use [official upstream issue tracker](https://sourceforge.net/p/sipe/feature-requests/) on Sourceforge.
