### ISSUE TITLE
Compilation failure purple-ft.c:1 nested extern declaration of purple_timeout_add

### ISSUE THREAD

**Issue by bergkatten** [tieto/sipe#153]
Hi,

Environment: Fedora 26

I'm building sipe from github against pidgin from hg clone https://bitbucket.org/pidgin/main

The autogen.sh succeeds but make fails with: 

purple-ft.c: In function ‘sipe_backend_ft_set_completed’:
purple-ft.c:148:2: error: implicit declaration of function ‘purple_timeout_add’; did you mean ‘purple_input_add’? [-Werror=implicit-function-declaration]
  purple_timeout_add(0, end_transfer_cb, FT_TO_PURPLE_XFER);
  ^~~~~~~~~~~~~~~~~~
  purple_input_add
purple-ft.c:148:2: error: nested extern declaration of ‘purple_timeout_add’ [-Werror=nested-externs]

Delopment environment:

libtool-2.4.6-17.fc26.x86_64
glib2-2.52.3-1.fc26.x86_64
intltool-0.51.0-8.fc26.noarch
glib2-devel-2.52.3-1.fc26.x86_64
gettext-devel-0.19.8.1-9.fc26.x86_64
pulseaudio-libs-glib2-10.0-4.fc26.x86_64
libxml2-devel-2.9.4-2.fc26.x86_64
libtool-ltdl-2.4.6-17.fc26.x86_64
gmime-2.6.23-2.fc26.x86_64
gstreamer1-plugins-base-devel-1.12.2-1.fc26.x86_64
glib2-devel-2.52.3-1.fc26.x86_64
libnice-devel-0.1.13-8.fc26.x86_64
nss-softokn-freebl-devel-3.32.0-1.2.fc26.x86_64
gettext-devel-0.19.8.1-9.fc26.x86_64
openssl-devel-1.1.0f-7.fc26.x86_64
gstreamer1-devel-1.12.2-1.fc26.x86_64
libxml2-devel-2.9.4-2.fc26.x86_64
farstream02-devel-0.2.7-4.fc26.x86_64

István

**Comment by bergkatten** [comment]
Update:
Just downloaded: https://launchpad.net/~sipe-collab/+archive/ubuntu/ppa/+files/pidgin-sipe_1.22.1+sipe-0+201708150946~ubuntu17.10.1.tar.xz

I used this process to build:

./autogen.sh
env PKG_CONFIG_PATH=/usr/local/lib/pkgconfig ./configure --enable-purple
make
sudo make install

This actually builds and seems to work in Fedora 26 now.

**Comment by xhaakon** [comment]
Reporter managed to figure out their issue, hence closing.
