### ISSUE TITLE
No longer able to use URL to join meetings, and "Protocol plugin RDP not installed"

### ISSUE THREAD

**Issue by dlpartain** [tieto/sipe#156]
Hi,

I use the software from the PPA all the time to join Skype for business-based meetings.  As of the last few days, I am unable to do two things that have worked previously.  My Ubuntu 16.04 machine  is fully updated.

1. I normally join the meeting by taking the URL, going to Accounts -> Account -> Join scheduled conference...   That URL might look like this:  https://meet.company.com/some.name/38MsxRs 

I can no longer do this.  I _can_ join the audio of the meeting if I instead fill in the email address of the meeting organizer and the conference ID, both of which I pull out of the URL.  When I do this, I then join the audio.

2. If someone starts sharing their desktop, I get the question if I want to accept it, do so, and get a pop-up error stating "Protocol plugin RDP not installed".  This is shown in the attached screenshot.
![screenshot from 2017-09-20 11-17-30](https://user-images.githubusercontent.com/4497928/30636999-67b7b0c0-9df7-11e7-9e26-d84e5acba52a.png)

I updated my system on Friday and pulled in some new software.  I can't guarantee that the update coincides with the beginning of problems, but I suspect so. 
I don't know exactly which packages are installed from the PPA, but this might be a reasonable list of installed packages I have on the machine right now.

ii  gir1.2-gplugin-0.0                          0.27+201606101045~ubuntu16.04.1
ii  gir1.2-gst-plugins-base-1.0                 1.8.3-1ubuntu0.2
ii  gstreamer1.0-alsa:amd64                     1.8.3-1ubuntu0.2
ii  gstreamer1.0-nice:amd64                     0.1.14~sipe-0+201701270901~ubuntu16.04.1
ii  gstreamer1.0-plugins-bad:amd64              1.8.3-1ubuntu0.2
ii  gstreamer1.0-plugins-bad-faad:amd64         1.8.3-1ubuntu0.2
ii  gstreamer1.0-plugins-bad-videoparsers:amd64 1.8.3-1ubuntu0.2
ii  gstreamer1.0-plugins-bad-faad:amd64         1.8.3-1ubuntu0.2
ii  gstreamer1.0-plugins-bad-videoparsers:amd64 1.8.3-1ubuntu0.2
ii  gstreamer1.0-plugins-base:amd64             1.8.3-1ubuntu0.2
ii  gstreamer1.0-plugins-base:i386              1.8.3-1ubuntu0.2
ii  gstreamer1.0-plugins-base-apps              1.8.3-1ubuntu0.2
ii  gstreamer1.0-plugins-base-apps              1.8.3-1ubuntu0.2
ii  gstreamer1.0-x:amd64                        1.8.3-1ubuntu0.2
ii  gstreamer1.0-x:i386                         1.8.3-1ubuntu0.2
ii  libfarstream-0.2-5:amd64                    0.2.8+sipe+collab-1+201701011925~ubuntu16.04.1
ii  libfreerdp2:amd64                           2.0.0~git20161130.1.e60d0d5+dfsg1+sipe-1~201709180958~ubuntu16.04.1 
ii  libfreerdp-client2:amd64                    2.0.0~git20161130.1.e60d0d5+dfsg1+sipe-1~201709180958~ubuntu16.04.1 
ii  libfreerdp-server2:amd64                    2.0.0~git20161130.1.e60d0d5+dfsg1+sipe-1~201709180958~ubuntu16.04.1 
ii  libfreerdp-shadow2:amd64                    2.0.0~git20161130.1.e60d0d5+dfsg1+sipe-1~201709180958~ubuntu16.04.1 
ii  libgplugin0                                 0.27+201606101045~ubuntu16.04.1
ii  libgplugin-loaders                          0.27+201606101045~ubuntu16.04.1
ii  libgplugin-lua                              0.27+201606101045~ubuntu16.04.1
ii  libgplugin-python                           0.27+201606101045~ubuntu16.04.1
ii  libgstreamer-plugins-bad1.0-0:amd64         1.8.3-1ubuntu0.2
ii  libgstreamer-plugins-base1.0-0:amd64        1.8.3-1ubuntu0.2
ii  libgstreamer-plugins-base1.0-0:i386         1.8.3-1ubuntu0.2
ii  libnice10:amd64                             0.1.14~sipe-0+201701270901~ubuntu16.04.1
ii  libpurple0                                  1:3.0.0~collab-1+201706131018~ubuntu16.04.1
ii  libpurple-bin                               1:3.0.0~collab-1+201706131018~ubuntu16.04.1
ii  libwinpr2:amd64                             2.0.0~git20161130.1.e60d0d5+dfsg1+sipe-1~201709180958~ubuntu16.04.1 
ii  libwinpr-tools2:amd64                       2.0.0~git20161130.1.e60d0d5+dfsg1+sipe-1~201709180958~ubuntu16.04.1 
ii  pidgin                                      1:3.0.0~collab-1+201706131018~ubuntu16.04.1
ii  pidgin-data                                 1:3.0.0~collab-1+201706131018~ubuntu16.04.1
ii  pidgin-sipe                                 1.22.1+sipe-0+201709181115~ubuntu16.04.1
ii  pidgin-data                                 1:3.0.0~collab-1+201706131018~ubuntu16.04.1
ii  pidgin-sipe                                 1.22.1+sipe-0+201709181115~ubuntu16.04.1
ii  remmina                                     1.2.0~rcgit+sipe-0+201703290633~ubuntu16.04.1 
ii  remmina-common                              1.2.0~rcgit+sipe-0+201703290633~ubuntu16.04.1
ii  remmina-plugin-rdp                          1.2.0~rcgit+sipe-0+201703290633~ubuntu16.04.1
ii  remmina-plugin-vnc                          1.2.0~rcgit+sipe-0+201703290633~ubuntu16.04.1
ii  remmina-common                              1.2.0~rcgit+sipe-0+201703290633~ubuntu16.04.1
ii  remmina-plugin-rdp                          1.2.0~rcgit+sipe-0+201703290633~ubuntu16.04.1
ii  remmina-plugin-vnc                          1.2.0~rcgit+sipe-0+201703290633~ubuntu16.04.1
ii  libwinpr-utils0.1:amd64                     1.1.0~git20140921.1.440916e+dfsg1-5ubuntu1.2

Thanks much,

David

**Comment by dlpartain** [comment]
Apparently, adding "?UseCdn=false" to the end of the URL that you paste into the pidgin box is a workaround to the first problem.

**Comment by mcirsta** [comment]
In Ubuntu 16.04 the problem seems to be:

Failed to load plugin: /usr/lib/x86_64-linux-gnu/remmina/plugins/remmina-plugin-rdp.so.
Error: libfreerdp.so.2: cannot open shared object file: No such file or directory


and then : 

ldd  /usr/lib/x86_64-linux-gnu/remmina/plugins/remmina-plugin-rdp.so | grep found
        libfreerdp.so.2 => not found
        libfreerdp-client.so.2 => not found
        libwinpr.so.2 => not found

 This is even though all deps needed were installed. It seems the remmina-plugin-rdp was not properly compiled or something.

  This is a regression for me after a recent update.

**Comment by xhaakon** [comment]
Apparently Remmina didn't get updated together with the last FreeRDP upgrade. I've triggered a new build on Launchpad that should fix this.

Please `apt-get update` and `apt-get install remmina-plugin-rdp`.

The latest version is now `remmina - 1.2.0~rcgit+sipe-0+201709221423~ubuntu16.04.1`.

**Comment by hexa00** [comment]
Somehow I had to reboot but remmina itself works now for me.
Pidgin screen sharing also works fine.
Thanks!

Note the "Can't use url to join meeting" is another issue ?, still to be fixed ?

**Comment by dlpartain** [comment]
Thank you!  Thank you!
