### ISSUE TITLE
Desktop sharing options not appearing w. pidgin-sipe 1.23

### ISSUE THREAD

**Issue by wizzor** [tieto/sipe#166]
On Ubuntu 16.04 options regarding desktop sharing do not appear with pidgin-sipe 1.23.0 (from repository or locally compiled from source).

Please advice, do I need extra software installed?

**Comment by xhaakon** [comment]
I've just tried installing pidgin-sipe in 16.04 and desktop sharing options appear as expected.

What is the exact version of the package you're trying to install and from which source? Please note that for you to be able to present your desktop, you should be installing from [ppa:sipe-collab](https://github.com/tieto/sipe/wiki/Sipe-collab-install#ubuntu). There's no such feature in distribution packages yet.

**Comment by wizzor** [comment]
Correction, had 17.04, installation from sipe-collab repository, versions:
sipe 1.23.0 and pidgin 3.0.0 (see below).

Unpacking pidgin-sipe (1.23.0+sipe-0+201712111032~ubuntu17.04.1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for desktop-file-utils (0.23-1ubuntu2) ...
Processing triggers for bamfdaemon (0.5.3+17.04.20170406-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for libc-bin (2.24-9ubuntu2.2) ...
Processing triggers for man-db (2.7.6.1-2) ...
Setting up pidgin (1:3.0.0~collab-1+201706131017~ubuntu17.04.1) ...

**Comment by xhaakon** [comment]
Tried PPA Sipe on a fresh 17.04 installation and I still can see 'Share my desktop' when I right-click a buddy or [while in a conference](https://github.com/tieto/sipe/wiki/Conference-with-desktop-sharing).

Could you please post the complete list of relevant packages you have? :
```
dpkg --list | grep -e sipe -e pidgin -e farstream -e remmina -e nice -e freerdp
```

**Comment by hesparza** [comment]
Same issue in Fedora 27, using xfce. 

I thought this was because of the version of the plugin (I installed from the default repos) so I got the code, compiled and installed it but still got the same result.

I have been looking for information on this regard and still cannot find an answer.

**Comment by Jellyfrog** [comment]
Same here!

Opensuse Tumbleweed
Pidgin 2.12.0 (libpurple 2.12.0)
Sipe 1.23.2

**Comment by muratg** [comment]
Same issue here.

@xhaakon, perhaps this helps:

```
git:(master) pacman -Q  |  grep -e sipe -e pidgin -e farstream -e remmina -e nice -e freerdp
farstream 0.2.8-1
freerdp 1:2.0.0_rc1-2
libnice 0.1.14-1
pidgin 2.13.0-1
pidgin-sipe 1.23.2-1
remmina 1:1.2.0rcgit.27-1
```

**Comment by mbrand** [comment]
Same issue on my side.
I also noticed that the "remote desktop client" configuration is a freetext input, while i often read that it should be a dropdown. 

```
pacman -Q  |  grep -e sipe -e pidgin -e farstream -e remmina -e nice -e freerdp
farstream 0.2.8-1
freerdp 1:2.0.0_rc2-1
libnice 0.1.14+70+gfb2f1f7-1
pidgin 2.13.0-1
pidgin-sipe 1.23.2-1
remmina 1:1.2.0rcgit.29-1
```

**Comment by xambroz** [comment]
@hesparza on Fedora 27 you need also package purple-sipe and remmina-plugins-rdp.
```
dnf -y install pidgin pidgin-sipe purple-sipe remmina remmina-plugins-rdp
```
Also it is recommended to install openh264 from fedora-cisco repository and to recompile the freerdp package with the parameters --with=ffmpeg --with=openh264 to enable the codec which from legal/political reasons might not be there in the public free repository of Fedora:
```
dnf -y config-manager --set-enabled fedora-cisco-openh264
dnf -y install openhpi openh264 openh264-devel mozilla-openh264 gstreamer1-plugin-openh264

# Rebuild latest freerdp package from src.rpm
# Go to the Fedora build for freerdp - https://koji.fedoraproject.org/koji/packageinfo?packageID=11176
# Take the last package successfully built - for example https://koji.fedoraproject.org/koji/buildinfo?buildID=1067383
# Download the src.rpm - for example https://kojipkgs.fedoraproject.org//packages/freerdp/2.0.0/41.20180405gita9ecd6a.fc27/src/freerdp-2.0.0-41.20180405gita9ecd6a.fc27.src.rpm
# Rebuild with the x264 enabled

rpmbuild --rebuild freerdp-2.0.0-41.20180405gita9ecd6a.fc27.src.rpm --with=ffmpeg --with=openh264
```

**Comment by hesparza** [comment]
It took me some time to figure out the different errors I was getting first while trying to use the fedora-cisco-penh254 repo and then during compilation but after it compiled correctly it indeed works!

Thank you very much @xambroz!! your help is well appreciated.

I'm placing here the dependencies I had to install in order to be able to compile:

When running:
`dnf -v -y install openhpi openh264 openh264-devel mozilla-openh264 gstreamer1-plugin-openh264`

it was failing for me, so I had to run:
```
sudo dnf --disablerepo=\* --enablerepo=updates update --refresh
sudo dnf update
dnf -y install openhpi openh264 openh264-devel mozilla-openh264 gstreamer1-plugin-openh264
```
I got the first 2 from [here](https://bugzilla.redhat.com/show_bug.cgi?id=1445817) from @Abed 's comment on 2018-05-01 12:03:14 EDT.

After that I install several dependencies in the following order (of course you can compress all of them to maybe one or two install instructions):

Note: notice how I had to also remove the freerdp and libwinpr I had already installed.

```
dnf -y install openhpi openh264 openh264-devel mozilla-openh264 gstreamer1-plugin-openh264
dnf install rpmdevtools
dnf install alsa-lib-devel.x86_64 cups-devel.x86_64 gsm-devel.x86_64 libXdamage-devel.x86_64 libXinerama-devel.x86_64 libXrandr-devel.x86_64 libXv-devel.x86_64 libjpeg-turbo-devel.x86_64 libxkbfile-devel.x86_64 pam-devel.x86_64 xmlto.x86_64
dnf install https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-27.noarch.rpm https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-27.noarch.rpm
dnf install ffmpeg-libs.x86_64
dnf install ffmpeg-devel.x86_64
dnf install pcsc-lite-devel.x86_64 pulseaudio-libs-devel.x86_64 systemd-devel.x86_64
dnf install mock
dnf install libXfixes-devel.x86_64 libXfixes.x86_64
dnf install libXcursor-devel.x86_64 libXcursor.i686
dnf install libXi.x86_64 libXi-devel.x86_64
dnf remove freerdp-server.x86_64 freerdp.x86_64
dnf install freerdp-2.0.0-41.20180405gita9ecd6a.fc27.x86_64.rpm freerdp-server-2.0.0-41.20180405gita9ecd6a.fc27.x86_64.rpm
dnf remove freerdp-libs.x86_64
dnf remove freerdp-libs.x86_64 libwinpr
```
At this point I was able to compile successfully. And then I run the following to install all the compiled rpms:

```
dnf install freerdp-2.0.0-41.20180405gita9ecd6a.fc27.x86_64.rpm freerdp-debuginfo-2.0.0-41.20180405gita9ecd6a.fc27.x86_64.rpm freerdp-debugsource-2.0.0-41.20180405gita9ecd6a.fc27.x86_64.rpm freerdp-devel-2.0.0-41.20180405gita9ecd6a.fc27.x86_64.rpm freerdp-libs-2.0.0-41.20180405gita9ecd6a.fc27.x86_64.rpm freerdp-libs-debuginfo-2.0.0-41.20180405gita9ecd6a.fc27.x86_64.rpm freerdp-server-2.0.0-41.20180405gita9ecd6a.fc27.x86_64.rpm freerdp-server-debuginfo-2.0.0-41.20180405gita9ecd6a.fc27.x86_64.rpm libwinpr-2.0.0-41.20180405gita9ecd6a.fc27.x86_64.rpm libwinpr-debuginfo-2.0.0-41.20180405gita9ecd6a.fc27.x86_64.rpm libwinpr-devel-2.0.0-41.20180405gita9ecd6a.fc27.x86_64.rpm
dnf -y install pidgin pidgin-sipe purple-sipe remmina remmina-plugins-rdp
```
Done.

**Comment by FloThinksPi** [comment]
@mbrand yes, also on my system under accounts -> your account -> Edit account -> advanced 
There is this field as freetext which was a dropdown according to other threads(https://forums.mauilinux.org/showthread.php?tid=24347)  describing this field:
![image](https://user-images.githubusercontent.com/5863788/41920574-4cf23ab2-7961-11e8-8800-9fdded15f487.png)
I set it to "Remmina" as well as "xfreerdp" but no change whatsoever. The share screen option is still missing in dropdowns and menus. I suspect the config not beeing read corrctly somewhere .

Fedora 28 with selfcompiled freerdp like @hesparza posted
```
pidgin-guifications-2.16-18.fc28.x86_64
pidgin-window-merge-0.3-10.fc28.x86_64
remmina-plugins-rdp-1.2.0-0.51.20180408.git.6b62986.fc28.x86_64
remmina-plugins-secret-1.2.0-0.51.20180408.git.6b62986.fc28.x86_64
freerdp-libs-debuginfo-2.0.0-41.20180405gita9ecd6a.fc28.x86_64
pidgin-2.13.0-1.fc28.1.x86_64
purple-libsteam-1.6.1-21.20180514git4a09c08.fc28.x86_64
freerdp-server-debuginfo-2.0.0-41.20180405gita9ecd6a.fc28.x86_64
libpurple-devel-2.13.0-1.fc28.1.x86_64
freerdp-server-2.0.0-41.20180405gita9ecd6a.fc28.x86_64
remmina-plugins-vnc-1.2.0-0.51.20180408.git.6b62986.fc28.x86_64
freerdp-devel-2.0.0-41.20180405gita9ecd6a.fc28.x86_64
remmina-plugins-exec-1.2.0-0.51.20180408.git.6b62986.fc28.x86_64
freerdp-debugsource-2.0.0-41.20180405gita9ecd6a.fc28.x86_64
sofia-sip-glib-1.12.11-16.fc28.x86_64
pidgin-indicator-1.0-6.fc28.x86_64
libpurple-2.13.0-1.fc28.1.x86_64
freerdp-2.0.0-41.20180405gita9ecd6a.fc28.x86_64
pidgin-libnotify-0.14-21.fc28.x86_64
remmina-plugins-nx-1.2.0-0.51.20180408.git.6b62986.fc28.x86_64
freerdp-libs-2.0.0-41.20180405gita9ecd6a.fc28.x86_64
pidgin-toobars-1.14-9.fc28.x86_64
pidgin-sipe-1.23.2-1.fc28.x86_64
pidgin-libsteam-1.6.1-21.20180514git4a09c08.fc28.noarch
remmina-1.2.0-0.51.20180408.git.6b62986.fc28.x86_64
freerdp-debuginfo-2.0.0-41.20180405gita9ecd6a.fc28.x86_64
remmina-plugins-xdmcp-1.2.0-0.51.20180408.git.6b62986.fc28.x86_64
pidgin-logviewer-0.2-22.20110228svn15.fc28.x86_64
purple-sipe-1.23.2-1.fc28.x86_64

```

**Comment by mooninite** [comment]
Fedora users: this repo is not what you have. Fedora ships upstream. The local sharing option was removed from upstream a while ago and has not been put back in. It's best if you ask upstream about it.

Upstream home page: http://sipe.sourceforge.net/
Upstream git: http://repo.or.cz/w/siplcs.git

**Comment by ImNtReal** [comment]
On my machine, I have the field for Remote desktop client empty, and it used Remmina to view a shared desktop. If there is an option for me to share mine, I don't see that, though.
```
 ~  pacman -Q  |  grep -e sipe -e pidgin -e farstream -e remmina -e nice -e freerdp                                                                                            29s  Mon 15 Oct 2018 11:32:50 AM EDT
farstream 0.2.8-1
freerdp 1:2.0.0_rc3-1
libnice 0.1.14+70+gfb2f1f7-1
pidgin 2.13.0-5
pidgin-sipe 1.23.3-1
remmina 1:1.2.32-1
telepathy-farstream 0.6.2-4
```

**Comment by onitake** [comment]
Been plagued by this problem as well, it was possible to join sessions (the pidgin-sipe would launch remmina for that), but not initiating them.
After rebuilding the plugin with the freerdp2 dev package installed, I can now also initiate sessions.

Here's the Debian bug I filed for that: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=915406

**Comment by mooninite** [comment]
Upstream recently turned client-side sharing support back on so you can initiate sharing instead of viewing only.

**Comment by FloThinksPi** [comment]
> Upstream recently turned client-side sharing support back on so you can initiate sharing instead of viewing only.

can confirm this. This should be closed as it was anyway a fedora ustream issue and is now fixed.
