### ISSUE TITLE
can only hear audio, not send it

### ISSUE THREAD

**Issue by brianjmurrell** [tieto/sipe#170]
After some relatively decent success with this, without changing anything on my end (no new packages installed, etc.) as of the last few weeks I have only been able to hear audio on lync meeting calls but nobody can hear my audio.

Pidgin is hearing my audio as the Tools->Voice/Video->Settings->Microphone test works fine.

Any ideas?

**Comment by antonjan** [comment]
I have the same problem and did check the seting as above all seems to work on the settings test

**Comment by brianjmurrell** [comment]
IIRC, I upgraded libnice to 0.1.14 to resolve this.  That should now be available in Fedora.
