### ISSUE TITLE
March 13th Windows Update Broke RDP Connectivity - SIPE Requires Latest FreeRDP to Work

### ISSUE THREAD

**Issue by grstitt** [tieto/sipe#176]
As per, https://github.com/FreeRDP/Remmina/issues/1512 the latest FreeRDP package is needed to be able RDP into Windows systems that have been updated with the March 13, 2018 updates.  Since there are dependency conflicts with installing the remmina packages directly from their PPA, ideally pidgin-sipe can be compiled against the latest freerdp build.

**Comment by xhaakon** [comment]
I've updated FreeRDP, Remmina and Sipe in 16.04 PPA. Please check if it solves your issue.

**Comment by grstitt** [comment]
Tested the latest update and it works when using Remmina directly and connecting to a WIndows system, but when I try to join a Skype for Business presentation it no longer works.  It won't even bring up the window.  I ran the command from a command prompt, but didn't see any errors.

**Comment by raetsel99** [comment]
@xhaakon  a colleague has 16.04 and this fix appears to work fine.
I am on 17:10 and I hit this bug, Will there be an update of  remmina  to update it to 1.2.0-rcgit-27-0 in your PPA for 17.10 ?
I  have had  to uninstall pidgin-sipe and use  the 1.2.0-rcgit-27-0 version from the main remmina PPA (remmina-ppa-team-ubuntu-remmina-next-artful) currently to allow me to connect to windows with correct negotiation.

When I try to install pidgin-sipe I have conflicts

The following packages have unmet dependencies.
 freerdp2-x11 : Depends: libfreerdp-client2 (>= 2.0.0~git201803141334-0+remmina201803141402.rf8baeb7.d29dd283~ubuntu17.10.1) but it is not going to be installed
                Depends: libfreerdp2 (>= 2.0.0~git201803141334-0+remmina201803141402.rf8baeb7.d29dd283~ubuntu17.10.1) but it is not going to be installed
                Depends: libwinpr2 (>= 2.0.0~git201803141334-0+remmina201803141402.rf8baeb7.d29dd283~ubuntu17.10.1) but it is not going to be installed

**Comment by xhaakon** [comment]
@raetsel99 I've updated freerdp and remmina packages in 17.10 PPA, please check.

**Comment by raetsel99** [comment]
@xhaakon yes works great thanks. I can use Remmina with my patched Windows servers and have pidgin-sipe installed to connect to  Skype for Business.
