### ISSUE TITLE
Screen sharing doesn't work on Fedora 27

### ISSUE THREAD

**Issue by mathbagu** [tieto/sipe#180]
Hi,
The screen sharing feature doesn't work properly on Fedora 27. The error message says 

> You requested an H264 GFX mode for server 127.0.0.1, but your libfreerdp does not support H264. Please check Color Depth settings.

I have the same message when I try to connect to a windows remote server with Remmina if the Color Depth parameter is set to:
- GFX AVC444 (32 bpp)
- GFX AVC420 (32 bpp)
- GFX RFX (32 bpp)

but it's OK if I use "True color (32 bpp)".

**Package versions:**
- pidgin-2.12.0-3.fc27.x86_64
- pidgin-sipe-1.23.2-1.fc27.x86_64
- remmina-1.2.0-0.50.20180321.git.f467f19.fc27.x86_64
- remmina-plugins-rdp-1.2.0-0.50.20180321.git.f467f19.fc27.x86_64
- freerdp-libs-2.0.0-40.20180320gitde83f4d.fc27.x86_64
- freerdp-2.0.0-40.20180320gitde83f4d.fc27.x86_64

Is it a way to set the default Color Depth parameter?

**Comment by xhaakon** [comment]
This is probably the same issue with recent versions of Remmina for which there is [this unreleased fix](http://repo.or.cz/siplcs.git/commit/236e3e153c48542319efdf84e9e58eb62c3109b9).

I don't have any Fedora packages with the patch included, so to test it you'll have to build it yourself, sorry.

Alternatively, downgrading `remmina` and `remmina-plugins-rdp` may also be a temporary solution until new Sipe gets released.

**Comment by mathbagu** [comment]
As a workaround, I configured pidgin to use `xfreerdp` instead of `remmina`

**Comment by mooninite** [comment]
This is fixed with the latest sipe / remmina combo. This can be closed.
