### ISSUE TITLE
No OTR

### ISSUE THREAD

**Issue by wizkidcom** [tieto/sipe#186]
Hello All,
I've just started using the PPA for sipe, and it has pidgin 3.00, but you don't have the pidgin-otr included, and the one in the stock repositories doesn't work.  Please add a working version of pidgin-otr to this repo so I can get encrypted chat back.  I do need that for work, and just because, big brother is watching....

**Comment by xhaakon** [comment]
Hi,
Starting from Ubuntu 18.04, the PPA uses the distribution version of Pidgin (currently 2.12.0), into which you can install the additional plugins you need. Please consider updating your system.
