### ISSUE TITLE
upstream the work

### ISSUE THREAD

**Issue by brianjmurrell** [tieto/sipe#190]
This repo (fork) has been around a while now and the work that has come out of it is great.

I wonder why though, after all of this time, none of the major enhancements (i.e. desktop sharing) have been upstreamed.

**Comment by luis-banuelos-chacon** [comment]
Where can I find this branch? I've been trying to build pidgin-sipe with desktop sharing support for Arch Linux but have not been able to find it anywhere.

**Comment by xhaakon** [comment]
I've just finished upstreaming desktop sharing, which was the last feature that had been sitting in the repo for a long time.

The major reason for the delays were the changes that had to be made to Pidgin and the underlying libraries first, then waiting for their new versions to be released. Only after the groundwork had been laid it made sense to finally get also the SIPE improvements upstream.

The commits that remain in this repository belong to a new feature - multiuser conference video - which is still a work in progress and doesn't perform well enough to be included in a stable SIPE release.

**Comment by brianjmurrell** [comment]
That's awesome.  Is there somewhere we can follow the upstreaming request?  It looks like upstream is at sourceforge but I can't see how PRs (or their equivalent) are opened there.

Much thanks!

**Comment by xhaakon** [comment]
> It looks like upstream is at sourceforge but I can't see how PRs (or their equivalent) are opened there

Upstream `mob` branch is opened for anybody to push, or alternatively one can email the patches to chemobejk@gmail.com.

The changes I was talking about are already merged to [mob](https://repo.or.cz/siplcs.git/shortlog/refs/heads/mob), so there's no "upstreaming request" you could follow.
