### ISSUE TITLE
Which tarball should I use: upstream/1.23.3 or 1.23.3?

### ISSUE THREAD

**Issue by jetm** [tieto/sipe#192]
From the sipe forum on SourceForge, I got the notion this repository has changes are not still in sipe upstream. Correct me if I am wrong.

By that notion, I was thinking to test all those changes that are not in sipe upstream, but I got confused with the two tarballs: [upstream/1.23.3](https://github.com/tieto/sipe/releases/tag/upstream%2F1.23.3) and [1.23.3](https://github.com/tieto/sipe/releases/tag/upstream%2F1.23.3). Which one should I download to test the changes are not in upstream?

p.d.: I generated both binaries from those but based on their weigh, they are the same.

**Comment by xhaakon** [comment]
Hi,

the code from branch [launchpad-next](https://github.com/tieto/sipe/commits/launchpad-next) is what you want. There's roughly 10 commits which aren't in SIPE upstream yet, but gradually moving there.

**Comment by jetm** [comment]
@xhaakon thank you for pointing out the right source. 

Would be too much ask for a Git tag, along with upstream/1.23.3 and 1.23.3, for that branch? So GitHub can generate a tarball and I could generate a new package for Linux. Thank you.

**Comment by xhaakon** [comment]
Hmm, tagging `launchpad-next` branch isn't really convenient to me as I rebase it on upstream `mob` often, and the goal is to get rid of it completely by upstreaming all the changes (within a period of a couple of weeks at most).

Still, it seems GitHub allows you to download a tarball with the latest sources on a branch like this:

  https://github.com/tieto/sipe/archive/launchpad-next.tar.gz

Does this help?

**Comment by jetm** [comment]
It makes sense.

The link helped. Thank you very much!
