### ISSUE TITLE
Pidgin 3.0 not available for Ubuntu Bionic

### ISSUE THREAD

**Issue by woulf** [tieto/sipe#196]
Hello,
while pidgin-sipe is available on the ppa for ubuntu 18.04 pidgin isn't.
therefore some options are not working as expected.
Can pidgin 3.0 be upload to the ppa?

regards,

Thibault

**Comment by xhaakon** [comment]
I have no plans to continue supporting experimental Pidgin 3.0. The version in official Ubuntu 18.04 repo should already have all essential changes needed to make the media features in sipe-collab PPA work (i.e. desktop sharing, video, filetransfer).

If you experience media issues with sipe-collab PPA and Ubuntu Pidgin, please open a bug here for that specific problem.
