### ISSUE TITLE
missing share desktop button

### ISSUE THREAD

**Issue by woulf** [tieto/sipe#197]
running pidgin-sipe 1.23.2 from the ppa:sipe-collab/ppa and either Pidgin 2.13.0 ppa:kip/pidgin or 2.12 (since no pidgin version is available for 18.04, see my other issue) from the official repo.
Ubuntu mate 18.04 fresh install
the "share my desktop" button is missing from both single person chat and skype for business meeting. I can see screen shared by others flawlessly.

**Comment by xhaakon** [comment]
Can't reproduce on Ubuntu 18.04. Enabling desktop sharing feature is a build-time setting, so "Share my desktop" option should be visible at least in buddy (single-person) menu at all times.

> running pidgin-sipe 1.23.2

The latest `pidgin-sipe` package in 18.04 PPA is `1.23.3+sipe-0+201811091804~ubuntu18.04.1`. Please check that you really have installed a package from sipe-collab PPA and not the one from the official repository, which seems to be the case.

The official Ubuntu packages do **not** include screen sharing.

**Comment by woulf** [comment]
And you where right :/
somehow it took a reboot for new version to be active.
Sorry for the time loss
