### ISSUE TITLE
Calls very crackly - both Tx & Rx

### ISSUE THREAD

**Issue by MikeCamel** [tieto/sipe#2]
Sound is so bad as to be unusable.

pidgin 1:3.0.0~collab-0.20359+201409041301~ubuntu14.04.1
pidgin-data 1:3.0.0~collab-0.20359+201409041301~ubuntu14.04.1
pidgin-dev 1:3.0.0~collab-0.20359+201409041301~ubuntu14.04.1
pidgin-sipe 1.18.3+collab-0.2857+201409181835~ubuntu14.04.1

Linux *******\* 3.13.0-36-generic #63-Ubuntu SMP Wed Sep 3 21:30:07 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

**Comment by MikeCamel** [comment]
Test call enough to show the problem: direct Lync calls and calls to external phones also affected.  Sound generally fine otherwise (spotify, videos, Skype and Lync in a Windows VM all great).

**Comment by MikeCamel** [comment]
No improvement with the latest Trusty Tahr versions:

pidgin (1:3.0.0~collab-0.20386+201410081029~ubuntu14.04.1) ...
pidgin-dev (1:3.0.0~collab-0.20386+201410081029~ubuntu14.04.1) ...
pidgin-sipe (1.18.3+collab-0.2859+201410021113~ubuntu14.04.1) ...
pidgin-data (1:3.0.0~collab-0.20386+201410081029~ubuntu14.04.1) ...

gstreamer0.10-nice:amd64 (0.1.7+sipe+collab-0.2071+201410081245~ubuntu14.04.1) ...
libpurple0 (1:3.0.0~collab-0.20386+201410081029~ubuntu14.04.1) ...
libpurple-bin (1:3.0.0~collab-0.20386+201410081029~ubuntu14.04.1) ...
libpurple-dev (1:3.0.0~collab-0.20386+201410081029~ubuntu14.04.1) ...

**Comment by MikeCamel** [comment]
Still no improvement.  Any news on whether this issue is being looked at, by any chance?

pidgin (1:3.0.0~collab-0.20421+201411281101~ubuntu14.04.1)
pidgin-data (1:3.0.0~collab-0.20421+201411281101~ubuntu14.04.1)
pidgin-dev (1:3.0.0~collab-0.20421+201411281101~ubuntu14.04.1)
pidgin-sipe (1.18.3+collab-0.2913+201412012146~ubuntu14.04.1)

libpurple-bin (1:3.0.0~collab-0.20421+201411281101~ubuntu14.04.1)
libpurple-dev (1:3.0.0~collab-0.20421+201411281101~ubuntu14.04.1)
libpurple0 (1:3.0.0~collab-0.20421+201411281101~ubuntu14.04.1)

**Comment by xhaakon** [comment]
Closing this issue as old and not reproducible on current version. Please reopen if you still experience this problem.
