### ISSUE TITLE
Problems with "show presentation"

### ISSUE THREAD

**Issue by suikula** [tieto/sipe#206]
Hi, 
Im using kubuntu 18.04, pidgin + sipe and I have problems with presentation (my share desktop is working but I cannot se others). Im using this setup on corporate lync system.

# remmina --version
Remmina plugin glibsecret (type=Secret) has registered but not yet initialized/activated. Initialization order is 2000.
Secret plugin glibsecret has been successfully initialized and will be your default secret plugin
org.remmina.Remmina - 1.3.8 (git n/a)

`
# xfreerdp --version
This is FreeRDP version 2.0.0-dev5 (n/a)

# remmina --full-version
Remmina plugin glibsecret (type=Secret) has registered but not yet initialized/activated. Initialization order is 2000.
Secret plugin glibsecret has been successfully initialized and will be your default secret plugin
org.remmina.Remmina - 1.3.8 (git n/a)

NAME                TYPE            DESCRIPTION                                                     PLUGIN AND LIBRARY VERSION
RDP                 Protocol        RDP - Remote Desktop Protocol                                   RDP Plugin: 1.3.8 (git n/a), Compiled with FreeRDP lib: 2.0.0-dev5 (n/a), Running with FreeRDP lib: 2.0.0-dev5 (rev n/a), H.264: Yes
RDPF                File            RDP - RDP File Handler                                          RDP Plugin: 1.3.8 (git n/a), Compiled with FreeRDP lib: 2.0.0-dev5 (n/a), Running with FreeRDP lib: 2.0.0-dev5 (rev n/a), H.264: Yes
RDPS                Preference      RDP - Preferences                                               RDP Plugin: 1.3.8 (git n/a), Compiled with FreeRDP lib: 2.0.0-dev5 (n/a), Running with FreeRDP lib: 2.0.0-dev5 (rev n/a), H.264: Yes
SPICE               Protocol        SPICE - Simple Protocol for Independent Computing Environments  1.3.8     
VNC                 Protocol        Remmina VNC Plugin                                              1.3.8     
VNCI                Protocol        Remmina VNC listener Plugin                                     1.3.8     
glibsecret          Secret          Secure password storing in the GNOME keyring                    1.3.8     

Build configuration: HAVE_ARPA_INET_H=1 HAVE_ERRNO_H=1 HAVE_FCNTL_H=1 HAVE_NETDB_H=1 HAVE_NETINET_IN_H=1 HAVE_NETINET_TCP_H=1 HAVE_SYS_SOCKET_H=1 HAVE_SYS_UN_H=1 HAVE_TERMIOS_H=1 HAVE_UNISTD_H=1 WITH_APPINDICATOR=ON WITH_AVAHI=ON WITH_CUPS=ON WITH_FREERDP=ON WITH_FREERDP_MASTER=OFF WITH_GCRYPT=ON WITH_GETTEXT=ON WITH_ICON_CACHE=ON WITH_IPP=OFF WITH_KF5WALLET=ON WITH_LIBRARY_VERSIONING=ON WITH_LIBSECRET=ON WITH_LIBSSH=ON WITH_LIBVNCSERVER=ON WITH_MANPAGES=ON WITH_SPICE=ON WITH_SSE2=ON WITH_TRANSLATIONS=ON WITH_UPDATE_DESKTOP_DB=ON WITH_VTE=ON WITH_WWW=ON
Build type:          None
CFLAGS:              -g -O2 -fdebug-prefix-map=/build/remmina-QUhw9m/remmina-1.3.9+ppa201912222246.rb410f51.db29af8c~ubuntu18.04.1=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -Wall -g
Compiler:            GNU, 7.4.0
Target architecture: x64

# dpkg -l | grep freerdp
ii  freerdp2-x11                                    2.0.0~git201912200700-0+remmina201912200932.r97d9d0a.d873abbd~ubuntu18.04.1 amd64        RDP client for Windows Terminal Services (X11 client)
ii  libfreerdp-cache1.1:amd64                       1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1.18.04.1                         amd64        Free Remote Desktop Protocol library (cache library)
ii  libfreerdp-client1.1:amd64                      1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1.18.04.1                         amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp-client2-2:amd64                      2.0.0~git201912200700-0+remmina201912200932.r97d9d0a.d873abbd~ubuntu18.04.1 amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp-codec1.1:amd64                       1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1.18.04.1                         amd64        Free Remote Desktop Protocol library (codec library)
ii  libfreerdp-common1.1.0:amd64                    1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1.18.04.1                         amd64        Free Remote Desktop Protocol library (common library)
ii  libfreerdp-core1.1:amd64                        1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1.18.04.1                         amd64        Free Remote Desktop Protocol library (core library)
ii  libfreerdp-crypto1.1:amd64                      1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1.18.04.1                         amd64        Free Remote Desktop Protocol library (freerdp-crypto library)
ii  libfreerdp-gdi1.1:amd64                         1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1.18.04.1                         amd64        Free Remote Desktop Protocol library (GDI library)
ii  libfreerdp-locale1.1:amd64                      1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1.18.04.1                         amd64        Free Remote Desktop Protocol library (locale library)
ii  libfreerdp-plugins-standard:amd64               1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1.18.04.1                         amd64        RDP client for Windows Terminal Services (plugins)
ii  libfreerdp-primitives1.1:amd64                  1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1.18.04.1                         amd64        Free Remote Desktop Protocol library (primitives library)
ii  libfreerdp-rail1.1:amd64                        1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1.18.04.1                         amd64        Free Remote Desktop Protocol library (rail library)
ii  libfreerdp-server2-2:amd64                      2.0.0~git201912200700-0+remmina201912200932.r97d9d0a.d873abbd~ubuntu18.04.1 amd64        Free Remote Desktop Protocol library (server library)
ii  libfreerdp-shadow-subsystem2-2:amd64            2.0.0~git201912200700-0+remmina201912200932.r97d9d0a.d873abbd~ubuntu18.04.1 amd64        FreeRDP Remote Desktop Protocol shadow subsystem libraries
ii  libfreerdp-shadow2-2:amd64                      2.0.0~git201912200700-0+remmina201912200932.r97d9d0a.d873abbd~ubuntu18.04.1 amd64        FreeRDP Remote Desktop Protocol shadow libraries
ii  libfreerdp-utils1.1:amd64                       1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1.18.04.1                         amd64        Free Remote Desktop Protocol library (freerdp-utils library)
ii  libfreerdp2-2:amd64                             2.0.0~git201912200700-0+remmina201912200932.r97d9d0a.d873abbd~ubuntu18.04.1 amd64        Free Remote Desktop Protocol library (core library)
ii  libxfreerdp-client1.1:amd64                     1.1.0~git20140921.1.440916e+dfsg1-15ubuntu1.18.04.1                         amd64        Free Remote Desktop Protocol library (xfreerdp-client library)

# dpkg -l | grep -i libfreerdp2
ii  libfreerdp2-2:amd64                             2.0.0~git201912200700-0+remmina201912200932.r97d9d0a.d873abbd~ubuntu18.04.1 amd64        Free Remote Desktop Protocol library (core library)

# dpkg -l | grep -i remmina
ii  freerdp2-x11                                    2.0.0~git201912200700-0+remmina201912200932.r97d9d0a.d873abbd~ubuntu18.04.1 amd64        RDP client for Windows Terminal Services (X11 client)
ii  libfreerdp-client2-2:amd64                      2.0.0~git201912200700-0+remmina201912200932.r97d9d0a.d873abbd~ubuntu18.04.1 amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp-server2-2:amd64                      2.0.0~git201912200700-0+remmina201912200932.r97d9d0a.d873abbd~ubuntu18.04.1 amd64        Free Remote Desktop Protocol library (server library)
ii  libfreerdp-shadow-subsystem2-2:amd64            2.0.0~git201912200700-0+remmina201912200932.r97d9d0a.d873abbd~ubuntu18.04.1 amd64        FreeRDP Remote Desktop Protocol shadow subsystem libraries
ii  libfreerdp-shadow2-2:amd64                      2.0.0~git201912200700-0+remmina201912200932.r97d9d0a.d873abbd~ubuntu18.04.1 amd64        FreeRDP Remote Desktop Protocol shadow libraries
ii  libfreerdp2-2:amd64                             2.0.0~git201912200700-0+remmina201912200932.r97d9d0a.d873abbd~ubuntu18.04.1 amd64        Free Remote Desktop Protocol library (core library)
ii  libwinpr-tools2-2:amd64                         2.0.0~git201912200700-0+remmina201912200932.r97d9d0a.d873abbd~ubuntu18.04.1 amd64        Windows Portable Runtime Tools library
ii  libwinpr2-2:amd64                               2.0.0~git201912200700-0+remmina201912200932.r97d9d0a.d873abbd~ubuntu18.04.1 amd64        Windows Portable Runtime library
ii  remmina                                         1.3.9+ppa201912222246.rb410f51.db29af8c~ubuntu18.04.1                       amd64        GTK+ Remote Desktop Client
ii  remmina-common                                  1.3.9+ppa201912222246.rb410f51.db29af8c~ubuntu18.04.1                       all          Common files for Remmina
ii  remmina-plugin-rdp:amd64                        1.3.9+ppa201912222246.rb410f51.db29af8c~ubuntu18.04.1                       amd64        RDP plugin for Remmina
ii  remmina-plugin-secret:amd64                     1.3.9+ppa201912222246.rb410f51.db29af8c~ubuntu18.04.1                       amd64        Secret plugin for Remmina
ii  remmina-plugin-spice:amd64                      1.3.9+ppa201912222246.rb410f51.db29af8c~ubuntu18.04.1                       amd64        Spice plugin for Remmina
ii  remmina-plugin-vnc:amd64                        1.3.9+ppa201912222246.rb410f51.db29af8c~ubuntu18.04.1                       amd64        VNC plugin for Remmina

# xfreerdp --help | grep -E -e relax-order -e glyph
    +glyph-cache                      Enable Glyph cache (experimental)
    /relax-order-checks               Do not check if a RDP order was announced

`

This is where it crashes..
`(org.remmina.Remmina:23919): GLib-CRITICAL **: 15:38:20.830: g_str_has_prefix: assertion 'str != NULL' failed
[15:38:21:457] [23919:29296] [WARN][com.freerdp.core.gcc] - Server uses non-advertised encryption method 0x00000000
[15:38:23:457] [23919:29296] [ERROR][com.freerdp.codec] - Chroma subsampling unimplemented
[15:38:23:457] [23919:29296] [ERROR][com.freerdp.core.fastpath] - Fastpath update Bitmap [1] failed, status 0
[15:38:23:457] [23919:29296] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data: fastpath_recv_update() - -1
[15:38:23:457] [23919:29296] [ERROR][com.freerdp.core.fastpath] - fastpath_recv_update_data() fail
[15:38:23:457] [23919:29296] [ERROR][com.freerdp.core.transport] - transport_check_fds: transport->ReceiveCallback() - -3
[15:38:23:457] [23919:29296] [ERROR][com.freerdp.core] - freerdp_check_fds() failed - 0
Could not check FreeRDP file descriptor
`

Can anyone help me with this? This use to work very well but after some update (not sure what was the update which broke this) it is not working anymore.

Thank you

**Comment by xhaakon** [comment]
Hi,

can you run remmina (which the log suggests is what's crashing) in `gdb` and make a stack trace of the crash?

You may find [Debug-HOWTO](https://github.com/tieto/sipe/wiki/Debug-HOWTO) helpful.

**Comment by suikula** [comment]
This issue can be closed.
Solution can be found:
https://github.com/FreeRDP/FreeRDP/issues/5822#
