### ISSUE TITLE
This message was not delivered to "name" because one or more recipients are offline:

### ISSUE THREAD

**Issue by Sepiidae** [tieto/sipe#25]
Connecting to Office365 Skype For Business we receive the following message when sending messages to any user in our organization. 

This message was not delivered to John Doe because the service is not available

**Software**
Running Ubuntu 14.04 x64
Pidgin 3.0.0devel
SIPE 1.20.1 

**Settings from Basic**
Username: account@somedomain.edu
Login is blank
Password is entered

**Settings from Advanced Tab:**
Connection Type: Auto
User Agent: UCCAPI/15.0.4745.1000 OC/15.0.4745.1000 (Skype for Business)
Authentication scheme: TLS-DSK

**Comment by xhaakon** [comment]
Can't reproduce with `UCCAPI/16.0.4339.1000 OC/16.0.4351.1000 (Skype for Business)` as a counterpart using the latest PPA `pidgin-sipe`.

Is this issue still affecting you?

**Comment by xhaakon** [comment]
Two weeks have passed without response; closing as unreproducible.

Feel free to reopen this issue if you can provide some additional information.
