### ISSUE TITLE
sipe-collab PPA broken for Ubuntu 15.10

### ISSUE THREAD

**Issue by linuxturtle** [tieto/sipe#29]
It's currently impossible to install pidgin-sipe on Ubuntu 15.10 due to packaging conflicts with dependent packages (libwinpr1, libfreerdp2, and libfreerdp-client2) in the sipe-collab PPA.

Currently, pidgin-sipe depends on remmina-plugin-rdp, which in wily, depends on libfreerdp1.  And the above packages all try to overwrite files provided by libfreerdp1.  Here are the relevant errors from "apt-get install pidgin-sipe":

`dpkg: error processing archive /var/cache/apt/archives/libwinpr1_2.0.0~git20160115.1.e2dbe5e+dfsg1-0~11~ubuntu15.10.1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libwinpr.so.1.1.0', which is also in package libfreerdp1:amd64 1.2.0~git20151218+dfsg-0wily2`

and

`dpkg: error processing archive /var/cache/apt/archives/libfreerdp2_2.0.0~git20160115.1.e2dbe5e+dfsg1-0~11~ubuntu15.10.1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libfreerdp.so.2.0.0', which is also in package libfreerdp1:amd64 1.2.0~git20151218+dfsg-0wily2`

and

`dpkg: error processing archive /var/cache/apt/archives/libfreerdp-client2_2.0.0~git20160115.1.e2dbe5e+dfsg1-0~11~ubuntu15.10.1_amd64.deb (--unpack):
 trying to overwrite '/usr/lib/x86_64-linux-gnu/libfreerdp-client.so.2.0.0', which is also in package libfreerdp1:amd64 1.2.0~git20151218+dfsg-0wily2`

**Comment by xhaakon** [comment]
libwinpr1, libfreerdp2, and libfreerdp-client2 should replace libfreerdp1.

I have fixed package dependencies in the PPA so that libfreerdp1 is now removed before the update can proceed.

In your case, please `apt-get purge` all packages from `dpkg --list | grep -e freerdp -e winpr | grep 1.2.0
` and then once again `apt-get update` and `apt-get install pidgin-sipe`.

Sorry for the inconvenience.

**Comment by linuxturtle** [comment]
Wow, that was fast! Thank you!  I can confirm that with the updated PPA, installing or upgrading pidgin-sipe from a generic 15.10 install now works smoothly, and libfreerdp1 is automatically superseded/replaced, and both pidgin-sipe and remmina seem to work afterwards.

Note that doing so leaves a lot of orphaned packages behind -- I don't know if you care about that, as it's fixable with a simple "apt-get autoremove", but here's the list of orphaned packages from doing a "dist-upgrade" after enabling the sipe-collab PPA, if you do care:

```
libfreerdp-cache1.1* libfreerdp-client1.1* libfreerdp-codec1.1* libfreerdp-common1.1.0* libfreerdp-core1.1* libfreerdp-crypto1.1* libfreerdp-gdi1.1* libfreerdp-locale1.1* libfreerdp-primitives1.1* libfreerdp-utils1.1* libwinpr-crt0.1* libwinpr-dsparse0.1* libwinpr-environment0.1* libwinpr-file0.1*
  libwinpr-handle0.1* libwinpr-heap0.1* libwinpr-input0.1* libwinpr-interlocked0.1* libwinpr-library0.1* libwinpr-path0.1* libwinpr-pool0.1* libwinpr-registry0.1* libwinpr-rpc0.1* libwinpr-sspi0.1* libwinpr-synch0.1* libwinpr-sysinfo0.1* libwinpr-thread0.1* libwinpr-utils0.1*

```

Thanks again for such a fast response!

**Comment by xhaakon** [comment]
@linuxturtle Those freerdp/winpr packages are now obsolete and expected to be left behind. I'm not sure if anything can be done to clean them up automatically. You can safely `apt-get autoremove` and forget about them.

**Comment by jgato** [comment]
maybe it is related, after updating today  I have this error

`/usr/bin/pidgin.orig: symbol lookup error: /usr/lib/libpidgin.so.20: undefined symbol: purple_desktop_item_get_string
`

**Comment by jgato** [comment]
Ok, I have found my mistake, I forget to also update pidgin package.
