### ISSUE TITLE
Doesn't work on Ubuntu 14.10 because of dependencies

### ISSUE THREAD

**Issue by ghost** [tieto/sipe#3]
libpurple0 wants libperl of >= 5.18 , there's 5.20 in Ubuntu 14.10, but probably not backward compatible. However libperl5.18 is in utopic-proposed updates, but then it depends on perl-base of 5.18 which is not available for Ubuntu 14.10 at all :-)

**Comment by xhaakon** [comment]
Builds for Ubuntu Utopic should be available again, closing as done. Feel free to reopen if you still have issues with the installation.
