### ISSUE TITLE
Support Video one2one

### ISSUE THREAD

**Issue by xnandersson** [tieto/sipe#31]
Using this thread as a place holder for Video support.

**Comment by xhaakon** [comment]
Initial support for _incoming_ video is now in PPA. So far only PC2PC calls were tested and are supported, and although Sipe sends a H264 stream, Lync isn't able to decode it. Picture quality is not stellar, but seems on par with Lync peer to peer video.

OpenGL and VA-API outputs don't work very well; make sure you have "X Window System" or "X Window System (Xv)" set in Voice/Video Pidgin preferences.

**Comment by xhaakon** [comment]
Both-way video should now work between Pidgins. Reportedly, some Skype for Business versions are also able to display our stream.

Issues which were limiting output video resolution have been fixed so Pidgin should now send picture in improved quality.

Playing video should work through any plugin including OpenGL, only VA-API still doesn't behave well. Make sure you do **not** have `gstreamer1.0-vaapi` installed.

**Comment by xhaakon** [comment]
Closing in favor of #68.
