### ISSUE TITLE
Shared desktop gives control to remote party

### ISSUE THREAD

**Issue by gy-lehel** [tieto/sipe#34]
If I share my desktop with a lync user, he/she will get control of the shared desktop. Please change default behavior to disallow control, and later provide possibility for controlling permissions given to parties.

**Comment by gy-lehel** [comment]
Works

**Comment by gy-lehel** [comment]
This issue came back with:

ii  pidgin                                                1:3.0.0~collab-0.20630+20160427 amd64                           graphical multi-protocol instant messaging client for X
ii  pidgin-data                                           1:3.0.0~collab-0.20630+20160427 all                             multi-protocol instant messaging client - data files
ii  pidgin-dbg                                            1:3.0.0~collab-0.20630+20160427 amd64                           Debugging symbols for Pidgin
un  pidgin-facebookchat                                   <none>                          <none>                          (no description available)
ii  pidgin-gnome-keyring                                  2.0~trusty-1                    amd64                           integrates pidgin (and libpurple) with the system keyring
ii  pidgin-otr                                            4.0.0-2                         amd64                           Off-the-Record Messaging plugin for Pidgin
rc  pidgin-ppa                                            0.0.9                           all                             Pidgin PPA
ii  pidgin-sipe                                           1.21.0+collab-201604260531+3207 amd64                           Pidgin plugin for MS Office Communicator and MS Lync
ii  pidgin-sipe-dbg                                       1.21.0+collab-201604260531+3207 amd64                           Pidgin plugin for MS Office Communicator and MS Lync (debug symbols)

**Comment by xhaakon** [comment]
Merging with #43.
