### ISSUE TITLE
Conferences created from SIPE can't share desktops

### ISSUE THREAD

**Issue by xhaakon** [tieto/sipe#35]
When a conference is created from Sipe (New Chat in Pidgin UI), its participants aren't able to initiate a desktop share because it's not "enabled for the conference". Works for meetings created via Lync or its web scheduler.

There must be some flag that needs setting at the time of the meeting creation.

**Comment by xhaakon** [comment]
FIxed in

```
pidgin-sipe - 1.21.0+sipe-0+201605100737~ubuntu16.04.1
pidgin-sipe - 1.21.0+sipe-0+201605100737~ubuntu15.10.1
pidgin-sipe - 1.21.0+sipe-0+201605100737~ubuntu15.04.1
pidgin-sipe - 1.21.0+sipe-0+201605100736~ubuntu14.04.1
```

**Comment by tcprdg** [comment]
Wil do today, thanks!

**Comment by tcprdg** [comment]
When I upgraded, I got 1.21.0+sipe-0+201605101223~ubuntu14.04.1. Is this correct?
