### ISSUE TITLE
Feature Request: Join conference, but without audio.

### ISSUE THREAD

**Issue by xnandersson** [tieto/sipe#38]
Reported by one tester:

"if I join a meeting with screen sharing, it brings up audio as well (I get no choice to join without audio) and also if you disconnect the audio it will stop the screen sharing and the only way I found to get it back up was to close the meeting window and rejoin"

**Comment by xhaakon** [comment]
> if you disconnect the audio it will stop the screen sharing

When you disconnect audio (close the call window), screen sharing should continue unaffected. I work like this all the time.

> the only way I found to get it back up was to close the meeting window and rejoin

If your screen sharing connection gets dropped, you can reconnect from the meeting window menu Conversation > More > Show presentation.

**Comment by xnandersson** [comment]
Yeah, if we don't want audio, we just chose not to accept the audio dialog. Closing.
