### ISSUE TITLE
telepathy build error

### ISSUE THREAD

**Issue by danboid** [tieto/sipe#39]
Arch Linux x64 w/ gcc 5.3.0

gcc -DHAVE_CONFIG_H -I. -I../..     -Werror -Wall -Wextra -Waggregate-return -Wcast-align -Wdeclaration-after-statement -Wdeprecated-declarations -Winit-self -Wmaybe-uninitialized -Wmissing-declarations -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wundef -Wunused-but-set-variable -DLOCALEDIR=\"/usr/local/share/locale\" -pthread -I/usr/include/telepathy-1.0 -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/dbus-1.0 -I/usr/lib/dbus-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -pthread -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I/usr/include/glib-2.0 -I/usr/lib/glib-2.0/include -I./../api -g -O2 -MT telepathy_sipe-telepathy-stubs.o -MD -MP -MF .deps/telepathy_sipe-telepathy-stubs.Tpo -c -o telepathy_sipe-telepathy-stubs.o `test -f 'telepathy-stubs.c' || echo './'`telepathy-stubs.c
telepathy-stubs.c:276:10: error: ‘struct sipe_backend_stream’ declared inside parameter list [-Werror]
          SIPE_UNUSED_PARAMETER gboolean blocking) { return(-1); }
          ^
telepathy-stubs.c:276:10: error: its scope is only this definition or declaration, which is probably not what you want [-Werror]
telepathy-stubs.c:272:6: error: no previous prototype for ‘sipe_backend_media_write’ [-Werror=missing-prototypes]
 gint sipe_backend_media_write(SIPE_UNUSED_PARAMETER struct sipe_backend_media _media,
      ^
cc1: all warnings being treated as errors
Makefile:726: recipe for target 'telepathy_sipe-telepathy-stubs.o' failed
make[4]: *_\* [telepathy_sipe-telepathy-stubs.o] Error 1

**Comment by xhaakon** [comment]
This experimental Sipe version doesn't target Telepathy right now, so such errors are to be expected.

I will fix this when I have some time to clean up and refactor the patches for inclusion in upstream Sipe. For the time being please `--disable-telepathy` when you run `configure`.
