### ISSUE TITLE
RFE:  Prevent remote users from having pointer control of desktop with desktop sharing... 

### ISSUE THREAD

**Issue by rbeldin** [tieto/sipe#43]
Something that I have noticed is that if I share a desktop, the remote user I am sharing with has the ability to move my pointer.   This can make for some 'exciting' or 'annoying' shared desktop sessions, depending on your point of view.  :)

In native Skype or Lync for Business, the user has the ability to 'share control'.   I can understand that this might be a bit of coding to implement, but would suggest until that is done, that the shared desktop disable the ability of remote users to access the mouse.

**Comment by rbeldin** [comment]
I just found out that this is a two-way street.  If I share a desktop,  not only are remote users able to move my pointer, I can move theirs.   

Perhaps related to: 

https://github.com/FreeRDP/Remmina/issues/489

**Comment by xhaakon** [comment]
Now it should be possible to turn desktop control on and off during pc2pc presentations through an item in the buddy menu (default is off):

![control](https://cloud.githubusercontent.com/assets/2165526/15248479/bde25792-191a-11e6-998d-e90620325356.png)

You have to be sharing the desktop with that buddy in order for the option to appear in the menu.

Lowest `pidgin-sipe` version required:

```
pidgin-sipe - 1.21.0+sipe-0+201605131208~ubuntu16.04.1
pidgin-sipe - 1.21.0+sipe-0+201605131208~ubuntu15.10.1
pidgin-sipe - 1.21.0+sipe-0+201605131208~ubuntu15.04.1
pidgin-sipe - 1.21.0+sipe-0+201605131208~ubuntu14.04.1
```

As to the multiuser conferences, it appears some negotiation between the presenter's server and the viewer's client has to take place on RDP protocol level before the control can be given. This is not implemented, or freerdp is not configured to handle control requests from the clients. For now, desktop control during conferences won't be available.

There's some information regarding the protocol which is likely responsible for requesting remote control available at [MSDN](https://msdn.microsoft.com/en-us/library/cc240493.aspx).

**Comment by xhaakon** [comment]
> not only are remote users able to move my pointer, I can move theirs

@rbeldin Yes, Remmina sends mouse events to the presenter's server all the time, and it's the server that decides if it will handle them or drop them. Remote control from SIPE has been working ever since application sharing was introduced, there only was no possibility to turn it off.

**Comment by xhaakon** [comment]
Two weeks from the fix release have passed without any further problems reported, so I consider this done an am closing the issue.
