### ISSUE TITLE
Audio deteriorates when Skype is running in the background

### ISSUE THREAD

**Issue by xnandersson** [tieto/sipe#45]
I've found that audio becomes quite bad if I happen to have Skype running in the background while using Pidgin Voice.

Right now the "solution" to the problem is to kill the skype process. I believe the problem lies with Skype so not sure if we can do anything about it.

**Comment by xhaakon** [comment]
If sound quality can be restored simply by shutting down Skype, this is out of scope. We can't fix proprietary software and if anything, you can try reporting bug against PulseAudio or whatever audio subsystem you're using.
