### ISSUE TITLE
Hard to separate playback/record volume dials from each-other 

### ISSUE THREAD

**Issue by xnandersson** [tieto/sipe#50]
Reported: "the audio windows show two dials which allow to modify the playback/record volume, but it doesn't actually display text which is which of the two."

**Comment by tmuehlhoff** [comment]
in fact the "mute" button could be besides the mic-dial as well to make it more clear. /TM

**Comment by xhaakon** [comment]
I guess the following simple change leaves no doubt which meter is which.

![input_volume](https://cloud.githubusercontent.com/assets/2165526/14739134/e9627cc6-0885-11e6-87a7-a27fe7213dbf.png)

```
pidgin - 1:3.0.0~collab-0.20630+201604221014~ubuntu16.04.1
pidgin - 1:3.0.0~collab-0.20630+201604221015~ubuntu15.10.1
pidgin - 1:3.0.0~collab-0.20630+201604221014~ubuntu15.04.1
pidgin - 1:3.0.0~collab-0.20630+201604220932~ubuntu14.04.1
```

(it still might take a few minutes before the packages appear in the PPA)

**Comment by tmuehlhoff** [comment]
great!
