### ISSUE TITLE
Crash when another user attempts to share the screen in a group conference

### ISSUE THREAD

**Issue by cristim** [tieto/sipe#55]

**Comment by xnandersson** [comment]
Hi @cristim can you please provide a back-trace as described here [1]?

[1] https://github.com/tieto/sipe/wiki/Debug-HOWTO

**Comment by tcprdg** [comment]
I too see this issue. xnandersson, let me see if i can spend some time in gathering the info you are looking for.

**Comment by xhaakon** [comment]
@tcprdg [here](https://github.com/tieto/sipe/issues/59#issuecomment-217796437)

We have a couple of duplicate or very similar issues. I'll close this one and merge it with #59.
