### ISSUE TITLE
Receiving a call from a real Lync client fails

### ISSUE THREAD

**Issue by mooninite** [tieto/sipe#6]
I can make a test call in Pidgin successfully. Recording and playback works in the test call.

I was called while logged in to Lync and Pidgin. Pidgin popped up the following error and I could not accept the call:

Call with sip:foo@bar.com failed

Error initializing the call. This probably denotes problem in installation of GStreamer or Farstream.

Message from Farsight: Could not build a new send codec bin: Could not link codec bin's main pads for : 117: audio G722 clock:8000 channels:0 params:(nil)

$ gst-inspect-1.0 | grep -i g722
rtp:  rtpg722pay: RTP audio payloader
rtp:  rtpg722depay: RTP audio depayloader
libav:  avdec_g722: libav G.722 ADPCM decoder
libav:  avenc_g722: libav G.722 ADPCM encoder

**Comment by mooninite** [comment]
Now it's not occurring, but I have not changed anything in Pidgin or Gstreamer. The same person called and I could answer. I can also make outgoing calls to anyone.

**Comment by mooninite** [comment]
Now it's happening again.

**Comment by rbeldin** [comment]
Happening to me...

**Comment by rbeldin** [comment]
Message from Farstream: Could not build a new send codec bin: Could not link codec bin's main pads for : 117: audio G722 clock:8000 channels:0 params:(nil)

gst-inspect-1.0 | grep -i g722
rtp:  rtpg722depay: RTP audio depayloader
rtp:  rtpg722pay: RTP audio payloader
libav:  avdec_g722: libav G.722 ADPCM decoder
libav:  avenc_g722: libav G.722 ADPCM encoder

Ubuntu 15.04 with ppa bits: 

ii  pidgin                                               1:3.0.0~collab-0.20489+201509091316~ubuntu15.04.1         amd64        graphical multi-protocol instant messaging client for X
ii  pidgin-data                                          1:3.0.0~collab-0.20489+201509091316~ubuntu15.04.1         all          multi-protocol instant messaging client - data files
ii  pidgin-plugin-pack                                   2.7.0-2                                                   amd64        Collection of Pidgin plugins
ii  pidgin-sipe                                          1.20.0+collab-201509111016+3082~ubuntu15.04.1             amd64        Pidgin plugin for MS Office Communicator and MS Lync

**Comment by xhaakon** [comment]
@rbeldin From your package listing it looks that you are missing several PPA packages, including patched GStreamer. Please make sure you installed everything from [this list](https://launchpad.net/~sipe-collab/+archive/ubuntu/ppa?field.series_filter=vivid).

**Comment by rbeldin** [comment]
Hi... 

I was pretty sure I added it so I added it again and then did an apt-get upgrade and no knew packages were installed. 

I think these are all the versions from the ppa: 

dpkg -l | grep collab
ii  gir1.2-farstream-0.2                                 0.2.7~sipe+collab-0.2991+201508211016~ubuntu15.04.1       amd64        Audio/Video communications framework: GObject-Introspection
ii  gstreamer0.10-nice:amd64                             0.1.13+sipe+collab-201509111616+2189~ubuntu15.04.1        amd64        ICE library (GStreamer 0.10 plugin)
ii  gstreamer1.0-nice:amd64                              0.1.13+sipe+collab-201509111616+2189~ubuntu15.04.1        amd64        ICE library (GStreamer plugin)
ii  libfarstream-0.2-2:amd64                             0.2.7~sipe+collab-0.2991+201508211016~ubuntu15.04.1       amd64        Audio/Video communications framework: core library
ii  libfarstream-0.2-dev                                 0.2.7~sipe+collab-0.2991+201508211016~ubuntu15.04.1       amd64        Audio/Video communications framework: development files
ii  libnice10:amd64                                      0.1.13+sipe+collab-201509111616+2189~ubuntu15.04.1        amd64        ICE library (shared library)
ii  libpurple-bin                                        1:3.0.0~collab-0.20489+201509091316~ubuntu15.04.1         all          multi-protocol instant messaging library - extra utilities
ii  libpurple0                                           1:3.0.0~collab-0.20489+201509091316~ubuntu15.04.1         amd64        multi-protocol instant messaging library
ii  pidgin                                               1:3.0.0~collab-0.20489+201509091316~ubuntu15.04.1         amd64        graphical multi-protocol instant messaging client for X
ii  pidgin-data                                          1:3.0.0~collab-0.20489+201509091316~ubuntu15.04.1         all          multi-protocol instant messaging client - data files
ii  pidgin-sipe                                          1.20.0+collab-201509111016+3082~ubuntu15.04.1             amd64        Pidgin plugin for MS Office Communicator and MS Lync

**Comment by xhaakon** [comment]
@rbeldin those look okay. Could you please check also `dpkg -l | grep '+sipe'` in order for us to see your versions of gst-plugins-\* as well?

You may try running pidgin from shell: `GST_DEBUG=3 pidgin --debug` to get some more detailed logs from gstreamer.

**Comment by rbeldin** [comment]
Ok, I'll turn on GST_DEBUG and capture that.  Here are the pidgin versions in the meantime.

dpkg -l | grep '+sipe'
ii  freerdp-x11                                          1.1.0~git20150628.1.084b365+dfsg-0+sipe~173~ubuntu15.04.1 amd64        RDP client for Windows Terminal Services (X11 client)
ii  gstreamer0.10-nice:amd64                             0.1.13+sipe+collab-201509111616+2189~ubuntu15.04.1        amd64        ICE library (GStreamer 0.10 plugin)
ii  gstreamer1.0-nice:amd64                              0.1.13+sipe+collab-201509111616+2189~ubuntu15.04.1        amd64        ICE library (GStreamer plugin)
ii  gstreamer1.0-plugins-bad:amd64                       1.4.5-1ubuntu2+sipe4                                      amd64        GStreamer plugins from the "bad" set
ii  gstreamer1.0-plugins-bad-faad:amd64                  1.4.5-1ubuntu2+sipe4                                      amd64        GStreamer faad plugin from the "bad" set
ii  gstreamer1.0-plugins-bad-videoparsers:amd64          1.4.5-1ubuntu2+sipe4                                      amd64        GStreamer videoparsers plugin from the "bad" set
ii  gstreamer1.0-plugins-good:amd64                      1.4.5-1ubuntu2+sipe1                                      amd64        GStreamer plugins from the "good" set
ii  gstreamer1.0-pulseaudio:amd64                        1.4.5-1ubuntu2+sipe1                                      amd64        GStreamer plugin for PulseAudio
ii  libfreerdp-client1.1:amd64                           1.1.0~git20150628.1.084b365+dfsg-0+sipe~173~ubuntu15.04.1 amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp-plugins-standard:amd64                    1.1.0~git20150628.1.084b365+dfsg-0+sipe~173~ubuntu15.04.1 amd64        RDP client for Windows Terminal Services (plugins)
ii  libfreerdp1.1:amd64                                  1.1.0~git20150628.1.084b365+dfsg-0+sipe~173~ubuntu15.04.1 amd64        Free Remote Desktop Protocol library (core library)
ii  libgstreamer-plugins-bad1.0-0:amd64                  1.4.5-1ubuntu2+sipe4                                      amd64        GStreamer development files for libraries from the "bad" set
ii  libgstreamer-plugins-good1.0-0:amd64                 1.4.5-1ubuntu2+sipe1                                      amd64        GStreamer development files for libraries from the "good" set
ii  libgstreamer-plugins-good1.0-dev                     1.4.5-1ubuntu2+sipe1                                      amd64        GStreamer development files for libraries from the "good" set
ii  libnice10:amd64                                      0.1.13+sipe+collab-201509111616+2189~ubuntu15.04.1        amd64        ICE library (shared library)
ii  libwinpr0.1:amd64                                    1.1.0~git20150628.1.084b365+dfsg-0+sipe~173~ubuntu15.04.1 amd64        Windows Portable Runtime library (winsock library)
ii  libxfreerdp-client1.1:amd64                          1.1.0~git20150628.1.084b365+dfsg-0+sipe~173~ubuntu15.04.1 amd64        Free Remote Desktop Protocol library (xfreerdp-client library)

**Comment by rbeldin** [comment]
I captured a full log which I can provide in email if you like.   It is rather large, but here is the area where we failed when someone attempted to call me: 

*(10:32:55) media: Error initializing the call. This probably denotes problem in installation of GStre
*amer or Farstream.

 Message from Farstream: Could not build a new send codec bin: Could not link codec bin's main pads fo
 r : 117: audio G722 clock:8000 channels:0 params:(nil)
 (10:32:55) GLib-GObject: g_value_set_object: assertion 'G_VALUE_HOLDS_OBJECT (value)' failed
 0:06:01.799810703 ESC[333m12830ESC[00m 0x7f35c7c5f280 ESC[32;01mFIXME  ESC[00m ESC[00;04m
  default gstutils.c:3643:gst_pad_create_stream_id_internal:dtmfsrc1:srcESC[00m Creating random stre
 am-id, consider implementing a deterministic way of creating a stream-id
 0:06:01.801435059 ESC[333m12830ESC[00m 0x7f35c7c9fb70 ESC[32;01mFIXME  ESC[00m ESC[00;04m
  default gstutils.c:3643:gst_pad_create_stream_id_internal:rtpdtmfsrc1:srcESC[00m Creating random s
 tream-id, consider implementing a deterministic way of creating a stream-id
 0:06:01.802990378 ESC[333m12830ESC[00m 0x7f35c7c9fb70 ESC[32;01mFIXME  ESC[00m ESC[00m            bas
 esink gstbasesink.c:3064:gst_base_sink_default_event:<fakesink7>ESC[00m stream-start event without gr
 oup-id. Consider implementing group-id handling in the upstream elements
 (10:32:55) Gtk: GtkDialog mapped without a transient parent. This is discouraged.
 (10:32:55) Gtk: GtkDialog mapped without a transient parent. This is discouraged.

....
A little bit later we tried again: 

 (10:33:34) backend-fs2: got new local candidate: 6
 (10:33:34) media: Error initializing the call. This probably denotes problem in installation of GStre*amer or Farstream.

_Message from Farstream: Could not build a new send codec bin: Could not link codec bin's main pads fo_r : 117: audio G722 clock:8000 channels:0 params:(nil)
 (10:33:34) GLib-GObject: g_value_set_object: assertion 'G_VALUE_HOLDS_OBJECT (value)' failed
 0:06:40.682953464 ESC[333m12830ESC[00m 0x7f35c820b400 ESC[32;01mFIXME  ESC[00m ESC[00;04m              default gstutils.c:3643:gst_pad_create_stream_id_internal:dtmfsrc2:srcESC[00m Creating random stre am-id, consider implementing a deterministic way of creating a stream-id
 0:06:40.683825369 ESC[333m12830ESC[00m 0x7f35c820b2d0 ESC[32;01mFIXME  ESC[00m ESC[00;04m              default gstutils.c:3643:gst_pad_create_stream_id_internal:rtpdtmfsrc2:srcESC[00m Creating random s tream-id, consider implementing a deterministic way of creating a stream-id
 0:06:40.684564950 ESC[333m12830ESC[00m 0x7f35c820b2d0 ESC[32;01mFIXME  ESC[00m ESC[00m            bas esink gstbasesink.c:3064:gst_base_sink_default_event:<fakesink12>ESC[00m stream-start event without g roup-id. Consider implementing group-id handling in the upstream elements
 (10:33:34) Gtk: GtkDialog mapped without a transient parent. This is discouraged.
 (10:33:34) Gtk: GtkDialog mapped without a transient parent. This is discouraged.

**Comment by xhaakon** [comment]
Please reopen if you're able to reproduce this issue on the current sipe-collab PPA version.

**Comment by framaglia** [comment]
I'm experiencing this issue. If I receive a call I got the error "Message from Farstream: Could not build a new send codec bin: Could not link codec bin's main pads for : 117: audio G722 clock:8000 channels:0 params:(nil)". Here is the log

```
(11:00:23)` sipe: sip_sec_verify_signature: message is:<NTLM><737C17CA><23><SIP Communications Service><USRILYNC13.gtk.gtech.com><06955dfea76246489369be472442ba2c><1><INVITE><sip:guest.manca.r@gtech.com><4bf0d89bfd><sip:guest.maglia.f@gtech.com><><sip:guest.manca.r@gtech.com><><> signature to verify is:01000000d5bc599d0bc6e23664000000
(11:00:23) sipe: NTLM MAC(): Extented Session Security
(11:00:23) sipe: NTLM MAC(): Key Exchange
(11:00:23) sipe: NTLM calculated MAC: 01000000D5BC599D0BC6E23664000000
(11:00:23) sipe: sip_transport_input: signature of incoming message validated
(11:00:23) sipe: process_input_message: msg->response(0),msg->method(INVITE)
(11:00:23) sipe: parsing address out of "Manca, Roberto"<sip:guest.manca.r@gtech.com>;tag=4bf0d89bfd;epid=7dcb82af83
(11:00:23) sipe: got sip:guest.manca.r@gtech.com
(11:00:23) sipe: sipe_session_add_call: new session for sip:guest.manca.r@gtech.com
(11:00:23) sipe: sipe_dialog_parse_routes: route <sip:access.gtech.com:443;transport=tls;opaque=state:Ci.R5e2cae00;lr;ms-route-sig=exEq4FcxzfTDuqudj4XvA0M0j-gX82MWwlcMtWiylz8yt0snIHg30sNgAA>;ms-rrsig=exIk-SICdXcUIA1BEQeswULsyn6PmG8eBLGUN4v1Ru9NV0snIHg30sNgAA;tag=84715EA7D38857B94C2BC02F1B0737C5
(11:00:23) sipe: sipe_dialog_parse_routes: route <sip:USRIWGFE.gtk.gtech.com:5061;transport=tls;ms-fe=USRILYNC13.gtk.gtech.com;lr>;tag=A3847B3CBA415C40F0213D7E69BC4275
(11:00:23) sipe: sipe_dialog_parse_routes: route <sip:ITROMFE.gtk.gtech.com:5061;transport=tls;ms-fe=ITROMLYNCFE2.gtk.gtech.com;opaque=state:F;lr>;tag=0DFB82AF18EF5987ADD20BFB73E6E765
(11:00:23) sipe: sipe_dialog_parse_routes: route <sip:ITROMFE.gtk.gtech.com:5061;transport=tls;ms-fe=ITROMLYNCFE1.gtk.gtech.com;opaque=state:T;lr>;tag=E4079C54EA43A34E3227CA9F3DEEE422
(11:00:23) backend-fs2: Creating hash table for sessions
(11:00:23) backend-fs2: connecting pad: success
(11:00:23) backend-fs2: create_src: setting source state to GST_STATE_PLAYING - it may hang here on win32
(11:00:23) backend-fs2: create_src: state set
(11:00:23) backend-fs2: Creating hash table for participants
(11:00:23) GLib-GObject: /build/buildd/glib2.0-2.40.2/./gobject/gsignal.c:2462: signal 'get-recvonly-filter' is invalid for instance '0x2140a40' of type 'FsNiceTransmitter'
(11:00:23) GLib-GObject: unable to set property 'relay-info' of type 'GPtrArray' from value of type 'GValueArray'
(11:00:23) media: Creating hash table for sessions
(11:00:23) gtkmedia: state: 0 sid: audio name: (null)
(11:00:23) sipe: sipe_media_state_changed_cb: 0 audio (null)

(11:00:23) gtkmedia: state: 0 sid: (null) name: sip:guest.manca.r@gtech.com
(11:00:23) sipe: sipe_media_state_changed_cb: 0 (null) sip:guest.manca.r@gtech.com

(11:00:23) gtkmedia: state: 0 sid: audio name: sip:guest.manca.r@gtech.com
(11:00:23) sipe: sipe_media_state_changed_cb: 0 audio sip:guest.manca.r@gtech.com

(11:00:23) sipe: sipmsg_strip_headers: removing ms-user-logon-data
(11:00:23) sipe: sipmsg_strip_headers: removing Max-Forwards
(11:00:23) sipe: sipmsg_strip_headers: removing Authentication-Info
(11:00:23) sipe: sipmsg_strip_headers: removing Content-Length
(11:00:23) sipe: sipmsg_strip_headers: removing P-Asserted-Identity
(11:00:23) sipe: sipmsg_strip_headers: removing Contact
(11:00:23) sipe: sipmsg_strip_headers: removing User-Agent
(11:00:23) sipe: sipmsg_strip_headers: removing Supported
(11:00:23) sipe: sipmsg_strip_headers: removing Ms-Conversation-ID
(11:00:23) sipe: sipmsg_strip_headers: removing Supported
(11:00:23) sipe: sipmsg_strip_headers: removing Supported
(11:00:23) sipe: sipmsg_strip_headers: removing Supported
(11:00:23) sipe: sipmsg_strip_headers: removing Supported
(11:00:23) sipe: sipmsg_strip_headers: removing Supported
(11:00:23) sipe: sipmsg_strip_headers: removing Supported
(11:00:23) sipe: sipmsg_strip_headers: removing ms-keep-alive
(11:00:23) sipe: sipmsg_strip_headers: removing Allow
(11:00:23) sipe: sipmsg_strip_headers: removing ms-subnet
(11:00:23) sipe: sipmsg_strip_headers: removing Accept-Language
(11:00:23) sipe: sipmsg_strip_headers: removing ms-endpoint-location-data
(11:00:23) sipe: sipmsg_strip_headers: removing Supported
(11:00:23) sipe: sipmsg_strip_headers: removing Supported
(11:00:23) sipe: sipmsg_strip_headers: removing Supported
(11:00:23) sipe: sipmsg_strip_headers: removing history-info
(11:00:23) sipe: sipmsg_strip_headers: removing Content-Type
(11:00:23) sipe: NTLM MAC(): Extented Session Security
(11:00:23) sipe: NTLM MAC(): Key Exchange
(11:00:23) sipe: NTLM calculated MAC: 01000000EFD6320EE60C372864000000
(11:00:23) sipe: 
MESSAGE START >>>>>>>>>> SIP - 2016-06-08T09:00:23.769304Z
SIP/2.0 180 Ringing
Record-Route: <sip:access.gtech.com:443;transport=tls;opaque=state:Ci.R5e2cae00;lr;ms-route-sig=exEq4FcxzfTDuqudj4XvA0M0j-gX82MWwlcMtWiylz8yt0snIHg30sNgAA>;ms-rrsig=exIk-SICdXcUIA1BEQeswULsyn6PmG8eBLGUN4v1Ru9NV0snIHg30sNgAA;tag=84715EA7D38857B94C2BC02F1B0737C5
Via: SIP/2.0/TLS 10.253.195.131:443;branch=z9hG4bKC29CC41F.0772B274777F1006;branched=FALSE;ms-internal-info="dld0xFnKjzcB8ZFVHa92NWB3kJ6fRnYmrurdO1gOx3KzR0snIHD9VonAAA"
Via: SIP/2.0/TLS 156.24.70.123:52559;branch=z9hG4bKAB88EE20.024D63F22BC36018;branched=FALSE;ms-received-port=52559;ms-received-cid=5D789900
Record-Route: <sip:USRIWGFE.gtk.gtech.com:5061;transport=tls;ms-fe=USRILYNC13.gtk.gtech.com;lr>;tag=A3847B3CBA415C40F0213D7E69BC4275
Via: SIP/2.0/TLS 172.26.4.9:16974;branch=z9hG4bKB567AC33.52C73E68D7BCE018;branched=FALSE;ms-received-port=16974;ms-received-cid=9D4FCD00
Record-Route: <sip:ITROMFE.gtk.gtech.com:5061;transport=tls;ms-fe=ITROMLYNCFE2.gtk.gtech.com;opaque=state:F;lr>;tag=0DFB82AF18EF5987ADD20BFB73E6E765
Via: SIP/2.0/TLS 172.26.4.14:48161;branch=z9hG4bK636ACE48.FE30348DD7A19018;branched=FALSE;ms-received-port=48161;ms-received-cid=479E8A00
Via: SIP/2.0/TLS 172.26.11.52:61228;ms-received-port=61228;ms-received-cid=3829F00
Record-Route: <sip:ITROMFE.gtk.gtech.com:5061;transport=tls;ms-fe=ITROMLYNCFE1.gtk.gtech.com;opaque=state:T;lr>;tag=E4079C54EA43A34E3227CA9F3DEEE422
From: "Manca, Roberto"<sip:guest.manca.r@gtech.com>;tag=4bf0d89bfd;epid=7dcb82af83
Call-ID: 06955dfea76246489369be472442ba2c
CSeq: 1 INVITE
To: <sip:guest.maglia.f@gtech.com>;epid=323286a3e3d4;tag=5791460385
Contact: <sip:guest.maglia.f@gtech.com;opaque=user:epid:U_cY8lh7DF6cuXbGfaT3xgAA;gruu>
Content-Length: 0
User-Agent: Purple/2.10.12 Sipe/1.21.0 (linux-x86_64; RTC/5.0)
Authorization: NTLM qop="auth", opaque="0337D718", realm="SIP Communications Service", targetname="USRILYNC13.gtk.gtech.com", crand="cfe0e258", cnum="18", response="01000000EFD6320EE60C372864000000"


MESSAGE END >>>>>>>>>> SIP - 2016-06-08T09:00:23.769304Z
(11:00:23) backend-fs2: got new local candidate: 9
(11:00:23) backend-fs2: got new local candidate: 8
(11:00:23) backend-fs2: got new local candidate: 7
(11:00:23) backend-fs2: got new local candidate: 9
(11:00:23) backend-fs2: got new local candidate: 8
(11:00:23) backend-fs2: got new local candidate: 7
(11:00:23) backend-fs2: got new local candidate: 1
(11:00:23) backend-fs2: got new local candidate: 2
(11:00:23) backend-fs2: got new local candidate: 3
(11:00:23) backend-fs2: got new local candidate: 4
(11:00:23) backend-fs2: got new local candidate: 5
(11:00:23) backend-fs2: got new local candidate: 6
(11:00:23) backend-fs2: got new local candidate: 1
(11:00:23) backend-fs2: got new local candidate: 2
(11:00:23) backend-fs2: got new local candidate: 3
(11:00:23) backend-fs2: got new local candidate: 4
(11:00:23) backend-fs2: got new local candidate: 5
(11:00:23) backend-fs2: got new local candidate: 6
(11:00:23) backend-fs2: Error setting encryption parameters: Does not support encryption
(11:00:23) backend-fs2: Error setting decryption parameters: Does not support decryption
(11:00:23) media: Error initializing the call. This probably denotes problem in installation of GStreamer or Farstream.

Message from Farsight: Could not build a new send codec bin: Could not link codec bin's main pads for : 117: audio G722 clock:8000 channels:0 params:(nil)
(11:00:23) sipe: sipmsg_strip_headers: removing Contact
(11:00:23) sipe: sipmsg_strip_headers: removing Content-Length
(11:00:23) sipe: sipmsg_strip_headers: removing User-Agent
(11:00:23) sipe: sipmsg_strip_headers: removing Authorization
(11:00:23) sipe: NTLM MAC(): Extented Session Security
(11:00:23) sipe: NTLM MAC(): Key Exchange
(11:00:23) sipe: NTLM calculated MAC: 0100000088D1E130E0BF064564000000
(11:00:23) sipe: 
```

I'm able to call but I hear just noise.

**Comment by xhaakon** [comment]
`User-Agent: Purple/2.10.12 Sipe/1.21.0 (linux-x86_64; RTC/5.0)`

@pollaiolo Can you show us the versions of the relevant packages you have installed? You can follow the procedure [on our wiki](https://github.com/tieto/sipe/wiki/Debug-HOWTO#package-versions). (The command will be a bit different if you aren't on a Debian-based distro.)

**Comment by framaglia** [comment]
Hello @xhaakon, thanks for quick reply. Here the info:

```
ii  gir1.2-farstream-0.1:amd64                            0.1.2-1ubuntu3                                                 amd64        Audio/Video communications framework: GObject-Introspection
ii  gir1.2-farstream-0.2                                  0.2.3-1ubuntu2                                                 amd64        Audio/Video communications framework: GObject-Introspection
ii  gstreamer0.10-nice:amd64                              0.1.14~sipe-0+201606031302~ubuntu14.04.1                       amd64        ICE library (GStreamer 0.10 plugin)
ii  gstreamer1.0-nice:amd64                               0.1.4-1                                                        amd64        ICE library (GStreamer plugin)
ii  gstreamer1.4-nice:amd64                               0.1.14~sipe-0+201606031302~ubuntu14.04.1                       amd64        ICE library (GStreamer plugin)
ii  libfarstream-0.1-0:amd64                              0.1.2-1ubuntu3                                                 amd64        Audio/Video communications framework: core library
ii  libfarstream-0.1-dev                                  0.1.2-1ubuntu3                                                 amd64        Audio/Video communications framework: development files
ii  libfarstream-0.2-2:amd64                              0.2.3-1ubuntu2                                                 amd64        Audio/Video communications framework: core library
rc  libfarstream-0.2-2-sipe:amd64                         0.2.7~sipe+collab-0.2991+201603172119~ubuntu14.04.1            amd64        Audio/Video communications framework: core library
ii  libfarstream-0.2-5-sipe:amd64                         0.2.8+sipe+collab-1+201605260749~ubuntu14.04.1                 amd64        Audio/Video communications framework: core library
ii  libfarstream-0.2-dev                                  0.2.3-1ubuntu2                                                 amd64        Audio/Video communications framework: development files
ii  libfreerdp-client2:amd64                              2.0.0~git20160503.1.f828595+dfsg1-0~201605121048~ubuntu14.04.1 amd64        Free Remote Desktop Protocol library (client library)
ii  libfreerdp-plugins-standard:amd64                     1.0.2-2ubuntu1                                                 amd64        RDP client for Windows Terminal Services (plugins)
ii  libfreerdp-server2:amd64                              2.0.0~git20160503.1.f828595+dfsg1-0~201605121048~ubuntu14.04.1 amd64        Free Remote Desktop Protocol library (server library)
ii  libfreerdp-shadow2:amd64                              2.0.0~git20160503.1.f828595+dfsg1-0~201605121048~ubuntu14.04.1 amd64        FreeRDP Remote Desktop Protocol shadow libraries
ii  libfreerdp1:amd64                                     1.0.2-2ubuntu1                                                 amd64        RDP client for Windows Terminal Services (library)
ii  libfreerdp2:amd64                                     2.0.0~git20160503.1.f828595+dfsg1-0~201605121048~ubuntu14.04.1 amd64        Free Remote Desktop Protocol library (core library)
ii  libgadu3                                              1:1.12.0-5~pidgin6.14.04                                       amd64        Gadu-Gadu protocol library - runtime files
ii  libnice-dev                                           0.1.14~sipe-0+201606031302~ubuntu14.04.1                       amd64        ICE library (development files)
ii  libnice10:amd64                                       0.1.14~sipe-0+201606031302~ubuntu14.04.1                       amd64        ICE library (shared library)
ii  libtelepathy-farstream-dev                            0.6.1-0ubuntu1                                                 amd64        Glue library between telepathy and farstream (development files)
ii  libtelepathy-farstream2:amd64                         0.4.0-3ubuntu2                                                 amd64        Glue library between telepathy and farstream - 0.4 series
ii  libtelepathy-farstream3:amd64                         0.6.1-0ubuntu1                                                 amd64        Glue library between telepathy and farstream
ii  libtelepathy-qt4-farstream2:amd64                     0.9.3-3ubuntu1                                                 amd64        Telepathy/Farsight integration - Qt 4 library
ii  pidgin                                                1:3.0.0~collab-1+201606060617~ubuntu14.04.1                    amd64        graphical multi-protocol instant messaging client for X
ii  pidgin-data                                           1:3.0.0~collab-1+201606060617~ubuntu14.04.1                    all          multi-protocol instant messaging client - data files
ii  pidgin-sipe                                           1.21.1+sipe-0+201605311247~ubuntu14.04.1                       amd64        Pidgin plugin for MS Office Communicator and MS Lync
ii  python-farstream                                      0.1.2-1ubuntu3                                                 amd64        Audio/Video communications framework: Python bindings
ii  remmina                                               1.2.0~rcgit+sipe-0+201606011019~ubuntu14.04.1                  amd64        remote desktop client for GNOME desktop environment
ii  remmina-common                                        1.2.0~rcgit+sipe-0+201606011019~ubuntu14.04.1                  all          common files for remmina remote desktop client
ii  remmina-plugin-rdp                                    1.2.0~rcgit+sipe-0+201606011019~ubuntu14.04.1                  amd64        RDP plugin for remmina remote desktop client
ii  remmina-plugin-vnc                                    1.2.0~rcgit+sipe-0+201606011019~ubuntu14.04.1                  amd64        VNC plugin for remmina remote desktop client
```

**Comment by xhaakon** [comment]
@pollaiolo I'm rather confused by that list, because the log you posted before doesn't look like it was created by Pidgin and Sipe from that installation:

`User-Agent: Purple/2.10.12 Sipe/1.21.0 (linux-x86_64; RTC/5.0)`

The log is from Pidgin 2.10, but sipe-collab PPA uses Pidgin 3.0 (as shown in your dpkg list). Do you have some parallel installation? Or perhaps have you changed your User-Agent in Advanced account preferences in Pidgin?

![settings](https://cloud.githubusercontent.com/assets/2165526/15890662/f24a12a8-2d70-11e6-8f05-745a10ebb6a8.png)

**Comment by framaglia** [comment]
I manually built pidgin3 and sipe and it wasn't working, then I installed everything from sipe-collab. Maybe something is messed up right now. I will clean everything and install from scratch. 
As for User-Agent I didn't set anything here. Thanks for your help.

**Comment by xhaakon** [comment]
@pollaiolo It seems to me as if you had mistakenly built Pidgin from 2.x branch (hence the wrong User-Agent) and the binary is now somewhere in PATH with precedence to /usr/bin/pidgin. Please clean that up before installing from the PPA.

**Comment by framaglia** [comment]
With fresh install I got:
(12:34:07) proxy: Unable to connect to destination host: Proxy protocol 'http' is not supported.
(12:34:07) proxy: Connection attempt failed: Unable to connect to destination host.
(12:34:07) connection: Connection error on 0x55b0420adae0 (reason: 0 description: SSL Connection Failed)
I don't know if I should open a new bug or I can continue here. Let me know if I should move somewhere else. Thanks.

**Comment by xhaakon** [comment]
@pollaiolo That's some unrelated issue; please open a new ticket for it if you will.
