### ISSUE TITLE
Feature Request - Add a button in chat window to join scheduled Lync meetings 

### ISSUE THREAD

**Issue by tcprdg** [tieto/sipe#62]
Hi,

Currently, to join a scheduled Lync conference, one has to go into Accounts-->Exchange Account-->Join Scheduled Conference. 

This is time consuming. Is it possible to add a button to the existing chat window or somewhere else such upon clicking, one should be able to paste URL and click join.

Thanks in advance!

**Comment by xhaakon** [comment]
The ways a protocol plugin can extend Pidgin's UI are quite constrained, hence the clumsy location of Join Conference command under several menu levels. Adding buttons into the UI isn't readily available, I'm afraid. I'll see what can be done with that.

Personally I'd prefer Pidgin to handle a conference URL when the user clicks on it in a browser or mail app, as discussed in #30.

**Comment by tcprdg** [comment]
Sure, thats good enough if adding button is a constraint due to reasons you mentioned. We can close this issue!
