### ISSUE TITLE
Smilies show up in conference join/part system messages

### ISSUE THREAD

**Issue by xhaakon** [tieto/sipe#70]
Apparently `:D` gets replaced:

![smilies](https://cloud.githubusercontent.com/assets/2165526/15206805/28f6783c-1822-11e6-813b-3e2fbf2770cf.png)

**Comment by xnandersson** [comment]
Yeah, and :D is not the only one. I think there need to be some markup added for "system-speak". For example

 <code><code>sip:Dav</code></code>.

**Comment by xhaakon** [comment]
Fix is building in

```
pidgin - 1:3.0.0~collab-1+201605121239~ubuntu16.10.1
pidgin - 1:3.0.0~collab-1+201605121239~ubuntu16.04.1
pidgin - 1:3.0.0~collab-1+201605121239~ubuntu15.04.1
pidgin - 1:3.0.0~collab-1+201605121240~ubuntu15.10.1
pidgin - 1:3.0.0~collab-1+201605121240~ubuntu14.04.1
```
