### ISSUE TITLE
Choppy/stuttering sound from microphone

### ISSUE THREAD

**Issue by overisberg** [tieto/sipe#77]
When I speak in a Lync meeting or even a test call my voice is very choppy/stuttering.

When I test Audio in Tools->Preferences->Voice/Video->Test Audio the sound is OK.
In Google hangout the sound is also OK... so I guess this could be a encoder problem in Pidgin/Sipe?!

I am running Pidgin on Ubuntu 14.04 and I have tried both USB headset and the microphone plug.

**Comment by MariaRigaki** [comment]
I have a similar issue that happens with a number of different input devices (USB, bluetooth, audio jack) and only in pidgin/Lync in Ubuntu 14.04 LTS. The USB headset is slightly less problematic, but still a lot of stutter. I have seen some errors in the logs related to gstreamer when I'm doing a test call (see attached part of the debug logs, not sure how much help they can be).

[pidgin_debug.txt](https://github.com/tieto/sipe/files/274213/pidgin_debug.txt)

**Comment by xnandersson** [comment]
Thank you for reporting. I have noticed that my microphone levels sometimes are set too high.

Also I have noticed that while I am using VPN the quality of the service sometimes degrades significantly.

I think that as we progress in our development we'll have to look at these issues in depth. I.e by doing packet capture, playbacks and identify where the bottle necks might be. It could be in the codec, the implementation, and the connection :-/

**Comment by MariaRigaki** [comment]
@xnandersson I agree it could be a number of things and it might not be the easiest to troubleshoot. Do let us know if you need traces and logs. Keep up the good work!

**Comment by tmuehlhoff** [comment]
same issue, happy to assist, if someone gets me a lead where to start troubleshooting,
I tried two different Plantronics Headsets so far. Lo Mic levels improve the situation, but I think it's not "really" affecting the problem. I also tried LAN instead of WLAN, but didnt get better.
Other applications are ok. (i.e. ekiga in my case)

prossible start:
- analog headset
- playout of wireshark trace

**Comment by xhaakon** [comment]
I had a look at the codecs Sipe uses for voice calls and noticed there was a bug in the selection algorithm which was causing that Sipe always picked a suboptimal PCMA codec that uses a lot of bandwidth. This could have been a reason of choppy audio on slow network connections.

Please update farstream and pidgin-sipe packages to at least these versions when they appear in the PPA and check if you observe any change in sound quality:

```
farstream-0.2 - 0.2.8+sipe+collab-1+201605231323~ubuntu16.04.1
farstream-0.2 - 0.2.8+sipe+collab-1+201605231323~ubuntu15.10.1
farstream-0.2-sipe - 0.2.8+sipe+collab-1+201605231323~ubuntu14.04.1

pidgin-sipe - 1.21.0+sipe-0+201605231325~ubuntu16.04.1
pidgin-sipe - 1.21.0+sipe-0+201605231325~ubuntu15.10.1
pidgin-sipe - 1.21.0+sipe-0+201605231325~ubuntu14.04.1  
```

Form now on, Sipe should prefer SIREN or G.722 audio encoding for calls.

**Comment by overisberg** [comment]
Initial testing is promising... I want to test more before we can close this ticket.

**Comment by overisberg** [comment]
We have verified this on more then one machine and audio quality is good so we can close this ticket.
