### ISSUE TITLE
Screen shared from Pidgin in a scheduled Lync conference is blank/dark

### ISSUE THREAD

**Issue by tcprdg** [tieto/sipe#78]
Hi,

My colleague created a Lync meeting (within our team and all of us are in same domain, in office, connected to same office network). When I start presenting, rest of them can only see a blank screen. Is this a known issue? Please let me know what logs help triage this issue further.

**Comment by xhaakon** [comment]
Hi, such an issue hasn't been reported yet. Please collect Pidgin log with libnice debug messages included by running:

```
GST_DEBUG=3 G_MESSAGES_DEBUG=all NICE_DEBUG=all,libnice-nice-verbose pidgin --debug
```

**Comment by xnandersson** [comment]
@tcprdg Does this issue persist?

**Comment by tcprdg** [comment]
@xnandersson , 

I did an apt-get and dist-upgrade today and got pidgin-sipe updated. After that, I had a lync meeting with our contractors where I shared my screen via pidgin. All worked well. I think this issue is fixed. Please close this issue. Or if its possible, keep it open until this Friday and close it if you dont hear anything from me. I have these meetings daily.

**Comment by xhaakon** [comment]
Closing the issue since the reporter says it's been fixed.
