### ISSUE TITLE
Problem with IRC protocol - missing symbol in libirc.so with  1:3.0.0~collab-1+201605202035~ubuntu16.04.1

### ISSUE THREAD

**Issue by rbeldin** [tieto/sipe#80]
None of my IRC channels were working this morning.  pidgin log shows: 

(Pidgin:16140): GPlugin-WARNING **: failed to query '/usr/lib/purple-3/libirc.so' with loader 'GPluginNativeLoader': Failed to open plugin '/usr/lib/purple-3/libirc.so': /usr/lib/purple-3/libirc.so: undefined symbol: irc_msg_auth
# dpkg -S /usr/lib/purple-3/libirc.so

libpurple0: /usr/lib/purple-3/libirc.so
# apt-cache madison libpurple0

libpurple0 | 1:3.0.0~collab-1+201605202035~ubuntu16.04.1 | http://ppa.launchpad.net/sipe-collab/ppa/ubuntu xenial/main amd64 Packages
libpurple0 | 1:2.10.12-0ubuntu5 | http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
    pidgin | 1:2.10.12-0ubuntu5 | http://us.archive.ubuntu.com/ubuntu xenial/universe Sources

**Comment by xhaakon** [comment]
IRC plugin fails to build in current Pidgin 3 master when Cyrus SASL is enabled at compile time; there's [upstream bugreport](https://developer.pidgin.im/ticket/17021) for it.

My quick workaround apparently wasn't enough to restore the plugin's functionality. I'll completely revert the changes in question on our branch and upload new Pidgin package to the PPA shortly.

**Comment by xhaakon** [comment]
Please update your `pidgin` package once new version becomes available (I assume it will take 20-40 minutes for the build to finish and be published).

```
 pidgin - 1:3.0.0~collab-1+201605231319~ubuntu15.10.1 
```

**Comment by rbeldin** [comment]
Thanks much.  I can confirm that 1:3.0.0~collab-1+201605231319~ubuntu16.04.1 restores IRC functionality.   Kudos to the sipe-collab team.  Who could ask for better than 2 hour response for a fix?  :)
