### ISSUE TITLE
4 minutes of initial annoying background noise when joining conference audio.

### ISSUE THREAD

**Issue by xnandersson** [tieto/sipe#85]
...after this time period sound is crystal clear. It is only the first minutes.

**Comment by xhaakon** [comment]
@xnandersson Try capturing a log with GST_DEBUG=5. Maybe there will be some clues reported by audio decoder or related elements.

**Comment by xnandersson** [comment]
@xhaakon I did that, and I have a log. But I don't think you want it. It is 365M big.

What I did saw, was huge deterioration in the sound quality when I enabled logging. It seems that as the i/o is running wild, it has a severe impact on the sound quality.

Perhaps i/o load is somehow related to this issue? :-I

**Comment by xhaakon** [comment]
@xnandersson Yeah, `GST_DEBUG=5` can be pretty extreme, even to the point the application becomes unresponsive. We should have started with something more sane like `GST_DEBUG=3,rtpjitterbuffer:5,sirendec:5,audiodecoder:5` to select only the messages from audio decoder.

You may try capturing less verbose log using the settings above or look into the huge one you already have and grep for lines that contain `sirendec` or `audiodecoder`.

**Comment by xhaakon** [comment]
@xnandersson Is this still relevant?

**Comment by xnandersson** [comment]
I recall that last time I called in this issue was no longer there. Closing.
