### ISSUE TITLE
No sound in voice calls on Purple/3.0.0devel Sipe/1.21.0

### ISSUE THREAD

**Issue by qugu** [tieto/sipe#87]
Hi!
I've installed sipe and pidgin-3 from the collaboration repository you guys maintain for ubuntu systems and I've run into an issue that there is absolutely no sound when I try to call someone. This is both in test call and external calls (so all calls). Calls shows as ongoing call. General audio is OK, i'm running pulse-audio on Ubuntu 15.10.

I'm attaching a verbose pidgin log, and a list of packages installed.

Hope you can help!
Thanks
Tim

[pidgin-packages.txt](https://github.com/tieto/sipe/files/284624/pidgin-packages.txt)
[pidgin-no-sound-verbose.txt](https://github.com/tieto/sipe/files/284662/pidgin-no-sound-verbose.txt)

**Comment by xhaakon** [comment]
Hi,

from the package list I see your installation is a mix of packages from Ubuntu and our PPA, most importantly

```
libnice10:amd64    0.1.13-0ubuntu2    amd64    ICE library (shared library)
```

seems like a stock Ubuntu version of libnice, which lacks many patches. This package plays an important role in establishing the connection path between the clients and you not having the up-to-date version might be the cause of the call issues you're observing.

So first of all make sure you updated all [packages listed here](https://launchpad.net/~sipe-collab/+archive/ubuntu/ppa/+packages?field.name_filter=&field.status_filter=published&field.series_filter=wily) to the versions mentioned therein. Then, if the problem persists, please create and attach a new log.

**Comment by qugu** [comment]
Hi, @xhaakon 
Thank you for your help. I've installed the latest set of packages and it's OK now, I have sound during voice calls.
